// 欧洲专项 —— 2026-06 第十五轮深挖
// 覆盖欧洲各国近一年(2025中-2026中)已开工投运 + 未来5年(到2030/2031)规划/在建。
// 聚焦既有数据集未收录的新项目；8 大品类覆盖(不含核电——9 大品类无核电桶)。
// region 一律 '欧洲'；coord 为 [经度,纬度] WGS-84；concat 进 ENERGY_EXTRA；
// index.html 在 data-oceania.js 之后、progress.js 之前加载。id 段 2700-2763。
window.ENERGY_EXTRA = (window.ENERGY_EXTRA || []).concat([
  // ===== 可再生能源发电（2700-2719）=====
  {"id":2700,"name":"埃拉斯莫光储氢综合体（西班牙）","en":"Erasmo Solar-Storage-Hydrogen (Saceruela)","country":"西班牙","region":"欧洲","cat":"renewable","coord":[-4.80,38.92],"cap":"1 GWp 光伏 + 储能 + 绿氢","inv":7,"invText":"约 7 亿美元","status":"规划","year":2027,"updated":"2025-10","owner":"开发商联合体","flagship":true,"desc":"欧洲规划最大单体光伏，1GWp 配储能绿氢。","detail":"位于西班牙雷阿尔城省萨塞鲁埃拉，规划装机达 1GWp，是欧洲规划中规模最大的单体光伏电站，并混合配置电池储能与绿氢制取。受益于西班牙逾 65GW 的获批光伏管线，2025 年推进审批与开发，是伊比利亚'吉瓦级光伏热潮'的标志项目。","progress":"2025 年推进审批，处于高级开发阶段"},
  {"id":2701,"name":"维茨尼茨光伏电站（德国）","en":"Witznitz Solar Park","country":"德国","region":"欧洲","cat":"renewable","coord":[12.48,51.13],"cap":"605 MWp","inv":5,"invText":"约 5 亿美元","status":"投运","year":2024,"updated":"2025-06","owner":"Move On Energy / Hansainvest","flagship":false,"desc":"德国最大光伏电站，莱比锡近郊褐煤区。","detail":"位于德国萨克森州莱比锡以南的原褐煤矿区，装机 605MWp，是德国已投运规模最大的光伏电站，无补贴依靠企业购电协议(PPA)建成，2024 年并网，象征德国煤区向太阳能转型，2025 年稳定运行。","progress":"2024 年并网，2025 年满发运行"},
  {"id":2702,"name":"赫德赖特海上风电（EnBW）","en":"He Dreiht Offshore Wind","country":"德国","region":"欧洲","cat":"renewable","coord":[6.40,54.20],"cap":"960 MW","inv":26,"invText":"约 26 亿美元（24 亿欧元）","status":"在建","year":2026,"updated":"2026-04","owner":"EnBW","flagship":true,"desc":"德国北海 960MW 海上风电，无补贴建设。","detail":"位于德国北海，由 EnBW 投建，装机 960MW、64 台 15MW 西门子歌美飒风机，是欧洲首批无补贴大型海上风电之一，将使 EnBW 海上装机翻番至近 2GW。截至 2025 年 10 月已装 23 台风机，计划 2026 年春全面投运。","progress":"2026 年风机安装推进，春季拟全容量投运"},
  {"id":2703,"name":"北海集群 A/B 海上风电（RWE）","en":"Nordseecluster A/B Offshore Wind","country":"德国","region":"欧洲","cat":"renewable","coord":[6.90,54.05],"cap":"1.6 GW（A+B）","inv":42,"invText":"约 42 亿美元（40 亿欧元）","status":"在建","year":2027,"updated":"2025-12","owner":"RWE / 挪威 Norges Bank","flagship":true,"desc":"德国北海尤伊斯特岛以北 1.6GW 风电集群。","detail":"位于德国北海尤伊斯特岛以北约 50 公里，由 RWE 牵头分两期开发，A 期约 660MW(2027 年投运)、B 期约 900MW，合计 1.6GW，是德国近期最大的海上风电集群之一，配套大型风机与海上升压站，向北威州工业区送电。","progress":"2025 年 A 期建设推进，B 期开发中"},
  {"id":2704,"name":"艾默伊登费尔阿尔法海上风电（荷兰）","en":"IJmuiden Ver Alpha Offshore Wind","country":"荷兰","region":"欧洲","cat":"renewable","coord":[3.70,52.85],"cap":"2 GW","inv":50,"invText":"约 50 亿美元","status":"在建","year":2029,"updated":"2025-12","owner":"荷兰招标中标方（含绿氢耦合）","flagship":true,"desc":"荷兰北海 2GW 超大型海上风电场。","detail":"位于荷兰北海离岸约 60 公里的艾默伊登费尔(IJmuiden Ver)区域 Alpha 场址，装机 2GW，2024 年 6 月授标、2025 年底推进最终投资决定，配套绿氢耦合与三角洲莱茵走廊外送，是荷兰能源转型的旗舰海上风电之一。","progress":"2025 年底推进 FID，目标 2029 投运"},
  {"id":2705,"name":"橙色风电海上风电（荷兰）","en":"OranjeWind Offshore Wind","country":"荷兰","region":"欧洲","cat":"renewable","coord":[4.00,52.62],"cap":"795 MW","inv":20,"invText":"约 20 亿美元","status":"在建","year":2028,"updated":"2025-07","owner":"RWE / TotalEnergies","flagship":false,"desc":"荷兰 795MW 海上风电，耦合绿氢电解。","detail":"位于荷兰北海，由 RWE 与道达尔合资开发，装机 795MW，所发电力部分耦合给道达尔在鹿特丹马斯弗拉克特的 ELYgator 绿氢电解项目，体现'海上风电+绿氢'一体化模式，2025 年推进建设。","progress":"2025 年建设推进，配套绿氢电解"},
  {"id":2706,"name":"科德林海上风电场（爱尔兰）","en":"Codling Wind Park","country":"爱尔兰","region":"欧洲","cat":"renewable","coord":[-5.90,53.10],"cap":"约 1.3 GW","inv":55,"invText":"约 55 亿美元","status":"规划","year":2030,"updated":"2025-09","owner":"EDF Renewables / Fred Olsen","flagship":true,"desc":"爱尔兰最大海上风电，都柏林外海 1.3GW。","detail":"位于爱尔兰东海岸都柏林外海，装机约 1.3GW，是爱尔兰规模最大的海上风电项目，由 EDF 与 Fred Olsen 合资开发。作为爱尔兰首轮 ORESS 海上风电招标的核心项目，2025 年推进规划许可与并网安排，目标 2030 年投运。","progress":"2025 年推进规划许可与开发"},
  {"id":2707,"name":"贝里克浅滩海上风电（苏格兰）","en":"Berwick Bank Offshore Wind","country":"英国","region":"欧洲","cat":"renewable","coord":[-2.00,56.30],"cap":"约 4.1 GW","inv":100,"invText":"约 100 亿美元（90 亿英镑）","status":"规划","year":2031,"updated":"2025-10","owner":"SSE Renewables","flagship":true,"desc":"全球规划最大海上风电之一，苏格兰外海 4.1GW。","detail":"位于苏格兰东部福斯湾外海，由 SSE 开发，装机约 4.1GW，是全球规划中规模最大的海上风电项目之一，可供约 600 万户家庭用电。2025 年推进苏格兰政府开发许可与并网，作为英国能源安全战略的旗舰项目，目标 2030 年代初投产。","progress":"2025 年推进开发许可审批"},
  {"id":2708,"name":"林根 GET H2 核心绿氢项目（RWE）","en":"GET H2 Nukleus Lingen (RWE)","country":"德国","region":"欧洲","cat":"renewable","coord":[7.32,52.52],"cap":"电解 300 MW","inv":5,"invText":"约 5 亿美元","status":"投运","year":2025,"updated":"2025-09","owner":"RWE","flagship":false,"desc":"欧洲最大可再生氢电解之一，林根 300MW。","detail":"位于德国下萨克森州林根，由 RWE 开发，首期 100MW 电解槽已于 2025 年启动调试，是 300MW GET H2 Nukleus 项目的第一部分，所产绿氢经管道供应道达尔洛伊纳炼厂，是欧洲规模最大的可再生氢电解项目之一。","progress":"2025 年首期 100MW 电解槽投运调试"},
  {"id":2709,"name":"荷兰氢能一号绿氢工厂（壳牌·鹿特丹）","en":"Holland Hydrogen I (Shell Rotterdam)","country":"荷兰","region":"欧洲","cat":"renewable","coord":[4.02,51.95],"cap":"电解 200 MW / 绿氢 2.19 万吨/年","inv":8,"invText":"约 8 亿美元","status":"投运","year":2025,"updated":"2025-06","owner":"Shell","flagship":true,"desc":"欧洲最大绿氢工厂之一，鹿特丹港 200MW。","detail":"位于荷兰鹿特丹港马斯弗拉克特，由壳牌投建，电解装机 200MW、年产绿氢约 2.19 万吨，电力来自荷兰海上风电(Hollandse Kust Noord)。作为欧洲投运规模最大的绿氢工厂之一，所产氢气经管道供应壳牌鹿特丹炼厂，2025 年投产。","progress":"2025 年建成投产"},
  {"id":2710,"name":"液空 ELYgator 绿氢电解（荷兰）","en":"Air Liquide ELYgator (Maasvlakte)","country":"荷兰","region":"欧洲","cat":"renewable","coord":[4.01,51.96],"cap":"电解 200 MW / 绿氢 2.3 万吨/年","inv":5,"invText":"约 5 亿美元（逾 5 亿欧元）","status":"在建","year":2027,"updated":"2025-07","owner":"Air Liquide","flagship":false,"desc":"鹿特丹港 200MW 绿氢电解，2025 作出 FID。","detail":"位于荷兰鹿特丹港马斯弗拉克特，由法国液空(Air Liquide)开发，2025 年 7 月作出最终投资决定，电解装机 200MW、年产绿氢约 2.3 万吨，电力来自 RWE-道达尔的 OranjeWind 海上风电，计划 2027 年投运，供应当地炼化与工业脱碳。","progress":"2025-07 作出 FID，目标 2027 投运"},
  {"id":2711,"name":"液空诺曼底绿氢项目（法国）","en":"Air Liquide Normand'Hy","country":"法国","region":"欧洲","cat":"renewable","coord":[0.30,49.50],"cap":"电解 200 MW（可扩至 GW 级）","inv":4,"invText":"约 4 亿美元","status":"规划","year":2027,"updated":"2025-06","owner":"Air Liquide","flagship":false,"desc":"法国诺曼底大型绿氢电解，服务工业脱碳。","detail":"位于法国诺曼底，由液空开发，首期电解装机 200MW(采用西门子能源 PEM)，远期可扩至吉瓦级，所产绿氢供应诺曼底炼化与化工集群脱碳，是法国氢能战略的旗舰项目之一，2025 年推进 FID。","progress":"2025 年推进 FID 与工程"},
  {"id":2712,"name":"BP 卡斯特利翁绿氢项目（西班牙）","en":"BP Castellón Green Hydrogen","country":"西班牙","region":"欧洲","cat":"renewable","coord":[-0.03,39.98],"cap":"电解 200 MW（一期）","inv":4,"invText":"约 4 亿美元","status":"在建","year":2026,"updated":"2025-08","owner":"BP","flagship":false,"desc":"西班牙卡斯特利翁炼厂配套绿氢电解。","detail":"位于西班牙卡斯特利翁 BP 炼厂，一期电解装机 200MW，计划 2026 年投运，所产绿氢用于炼厂脱碳并外供工业用户，是 BP 在西班牙打造绿氢枢纽(HyVal)的第一步，远期规划扩至更大规模。","progress":"2025 年一期建设推进，目标 2026 投运"},
  {"id":2713,"name":"莱茵兰 REFHYNE II 绿氢（壳牌·德国）","en":"REFHYNE II (Shell Rheinland)","country":"德国","region":"欧洲","cat":"renewable","coord":[6.97,50.83],"cap":"电解 100 MW / 绿氢 1.6 万吨/年","inv":3,"invText":"约 3 亿美元","status":"在建","year":2027,"updated":"2025-06","owner":"Shell","flagship":false,"desc":"德国莱茵兰炼厂 100MW 绿氢电解。","detail":"位于德国韦塞林壳牌莱茵兰能源化工园，电解装机 100MW、年产绿氢约 1.6 万吨，2024 年作出 FID，计划 2027 年投运，用于炼厂脱碳，是欧洲炼化绿氢示范的代表项目之一。","progress":"2024 年 FID，2025 年建设推进"},
  {"id":2714,"name":"奥胡斯地热区域供热（丹麦）","en":"Aarhus Geothermal District Heating","country":"丹麦","region":"欧洲","cat":"renewable","coord":[10.20,56.16],"cap":"110 MW 地热供热","inv":3,"invText":"约 3 亿美元","status":"在建","year":2030,"updated":"2025-09","owner":"Innargi / 奥胡斯供热","flagship":false,"desc":"欧盟最大地热区域供热系统，供奥胡斯。","detail":"位于丹麦奥胡斯，由 Innargi 开发，含 7 个站点 17 口井、供热能力 110MW，是欧盟规模最大的地热区域供热系统，建成后可满足该市约 20% 的区域供热需求，2025 年开钻，计划 2030 年前建成。","progress":"2025 年首批井开钻施工"},
  {"id":2715,"name":"格雷茨里德增强地热电站（德国）","en":"Eavor Geretsried Geothermal","country":"德国","region":"欧洲","cat":"renewable","coord":[11.60,47.85],"cap":"闭式增强地热（电+热）","inv":4,"invText":"约 4 亿美元","status":"在建","year":2026,"updated":"2025-12","owner":"Eavor","flagship":false,"desc":"巴伐利亚闭式增强地热旗舰，2025 年首次发电。","detail":"位于德国巴伐利亚格雷茨里德，由加拿大 Eavor 开发，采用闭式回路(Eavor-Loop)增强型地热技术，2025 年底首次向德国电网送电，目标提供基荷可再生电力与区域供热，是欧洲下一代地热(EGS)首批商业示范项目。","progress":"2025-12 首次并网发电，分阶段扩容"},
  {"id":2716,"name":"外道辛海上风电（英国）","en":"Outer Dowsing Offshore Wind","country":"英国","region":"欧洲","cat":"renewable","coord":[0.80,53.40],"cap":"约 1.5 GW","inv":60,"invText":"约 60 亿美元","status":"规划","year":2031,"updated":"2025-08","owner":"Corio / TEPCO / Gulf Energy","flagship":false,"desc":"英国林肯郡外海 1.5GW 海上风电。","detail":"位于英国东海岸林肯郡外海,装机约 1.5GW,可供约 160 万户家庭用电,由 Corio Generation 等开发。2025 年推进开发许可(DCO)审批与并网安排,是英国北海海上风电扩容的重要新增项目。","progress":"2025 年推进 DCO 审批"},
  {"id":2717,"name":"荷兰海岸西 Ecowende 海上风电","en":"Hollandse Kust West (Ecowende)","country":"荷兰","region":"欧洲","cat":"renewable","coord":[4.10,52.70],"cap":"760 MW","inv":20,"invText":"约 20 亿美元","status":"在建","year":2026,"updated":"2025-07","owner":"Ecowende（Shell / Eneco）","flagship":false,"desc":"生态友好型海上风电示范，荷兰海岸西。","detail":"位于荷兰北海'荷兰海岸西(Hollandse Kust West)'VII 区，由壳牌与 Eneco 合资的 Ecowende 开发，装机 760MW,采用生态友好设计(利于海洋生物与鸟类),是荷兰'自然共生'海上风电示范,2025 年建设推进,计划 2026 年投运。","progress":"2025 年建设推进,目标 2026 投运"},
  {"id":2718,"name":"波罗的电力海上风电（波兰）","en":"Baltic Power Offshore Wind","country":"波兰","region":"欧洲","cat":"renewable","coord":[18.20,55.00],"cap":"1.2 GW","inv":48,"invText":"约 48 亿美元（45 亿欧元）","status":"在建","year":2026,"updated":"2025-09","owner":"ORLEN / Northland Power","flagship":true,"desc":"波兰首个大型海上风电，波罗的海 1.2GW。","detail":"位于波兰波罗的海海域,由波兰 ORLEN 与加拿大 Northland Power 合资开发,装机 1.2GW、76 台 15MW 风机,是波兰首个建成的大型海上风电场,总投资约 45 亿欧元。2025 年海上施工推进,计划 2026 年投运,开启波兰海上风电时代。","progress":"2025 年海上基础与风机安装推进"},
  {"id":2719,"name":"托尔海上风电（丹麦）","en":"Thor Offshore Wind","country":"丹麦","region":"欧洲","cat":"renewable","coord":[7.60,56.40],"cap":"1 GW","inv":30,"invText":"约 30 亿美元","status":"在建","year":2027,"updated":"2025-08","owner":"RWE","flagship":false,"desc":"丹麦最大海上风电，北海 1GW。","detail":"位于丹麦西海岸北海海域,由 RWE 投建,装机约 1.08GW、72 台 15MW 风机,是丹麦迄今规模最大的海上风电场。2025 年海上施工推进,计划 2027 年全容量投运,部分电力配套绿氢与工业脱碳。","progress":"2025 年海上施工推进"},

  // ===== 输变电·电网（2720-2726）=====
  {"id":2720,"name":"第勒尼安海直流海缆（意大利）","en":"Tyrrhenian Link","country":"意大利","region":"欧洲","cat":"grid","coord":[12.00,39.50],"cap":"1000MW / 约 970 公里 HVDC","inv":38,"invText":"约 38 亿美元（37 亿欧元）","status":"在建","year":2028,"updated":"2026-01","owner":"Terna","flagship":true,"desc":"连接西西里-撒丁岛-本土，创最深海缆纪录。","route":[[15.0,38.2],[9.1,39.2]],"detail":"由意大利 Terna 投建的双极 HVDC 海底电缆,连接西西里岛、撒丁岛与意大利本土,总长约 970 公里、容量 1000MW。2025 年 12 月 Nexans 完成 2150 米水深的 500kV 海缆敷设,创世界最深 HVDC 海缆纪录,换流站计划 2028 年底建成,大幅增强地中海电网弹性与可再生消纳。","progress":"2026-01 完成创纪录深海海缆敷设"},
  {"id":2721,"name":"亚得里亚海直流海缆（意大利）","en":"Adriatic Link","country":"意大利","region":"欧洲","cat":"grid","coord":[14.50,42.50],"cap":"1000MW / 约 250 公里 HVDC","inv":15,"invText":"约 15 亿美元","status":"在建","year":2028,"updated":"2025-06","owner":"Terna","flagship":false,"desc":"连接马尔凯与阿布鲁佐的海底直流。","route":[[13.5,43.6],[14.2,42.4]],"detail":"由 Terna 投建的双极 HVDC 海底电缆,连接意大利中部马尔凯与阿布鲁佐大区,容量 1000MW、约 250 公里,增强意大利中南与中北分区电力交换。欧洲投资银行等提供 15 亿欧元融资,提升电网安全、效率与可再生消纳能力。","progress":"2025 年获 15 亿欧元融资,工程推进"},
  {"id":2722,"name":"狮链英荷海上互联（LionLink）","en":"LionLink Interconnector (UK–Netherlands)","country":"英国","region":"欧洲","cat":"grid","coord":[3.00,52.50],"cap":"1.8 GW HVDC 多端","inv":30,"invText":"约 30 亿美元","status":"规划","year":2032,"updated":"2025-09","owner":"National Grid / TenneT","flagship":true,"desc":"全球最大多端海上互联之一，连英荷与海上风电。","route":[[1.6,52.0],[4.0,52.6]],"detail":"由英国 National Grid 与荷兰 TenneT 合作开发的 1.8GW HVDC 多端互联,把北海海上风电同时接入英国与荷兰电网,可供约 250 万户用电。2026 年预期作出 FID,2030-2032 投运,是欧洲'海上电网'(混合互联)的标志性工程。","progress":"2025 年推进规划,FID 预期 2026"},
  {"id":2723,"name":"海链直流海缆（英国）","en":"Sea Link Interconnector","country":"英国","region":"欧洲","cat":"grid","coord":[1.40,51.40],"cap":"2 GW / 约 130 公里 HVDC","inv":20,"invText":"约 20 亿美元","status":"规划","year":2031,"updated":"2025-03","owner":"National Grid","flagship":false,"desc":"连接肯特与萨福克的英国内部直流海缆。","route":[[1.4,51.3],[1.6,52.0]],"detail":"由英国 National Grid 开发的 2GW HVDC 海底电缆,连接肯特郡佩格韦尔湾与萨福克海岸,约 130 公里,缓解英格兰东南电网拥堵、接纳更多海上风电。2025 年 3 月递交开发许可申请(DCO),目标 2030 年代初投运。","progress":"2025-03 递交 DCO 开发许可申请"},
  {"id":2724,"name":"莱茵-美因直流走廊（德国）","en":"Rhein-Main-Link (Amprion)","country":"德国","region":"欧洲","cat":"grid","coord":[8.50,50.00],"cap":"4×2GW HVDC 走廊","inv":30,"invText":"约 30 亿美元","status":"规划","year":2033,"updated":"2025-10","owner":"Amprion / 50Hertz","flagship":true,"desc":"把北部风电送往莱茵-美因负荷中心。","detail":"由 Amprion 与 50Hertz 合作的多回 HVDC 直流走廊,把德国北部及北海海上风电送往莱茵-美因(法兰克福)工业负荷中心,规划多回 ±525kV 各 2GW。是德国电网扩建(类似 SuedLink)的关键南向通道,2025 年推进审批,目标 2030 年代初建成。","progress":"2025 年推进规划与审批"},
  {"id":2725,"name":"波罗的三国电网欧洲同步工程","en":"Baltic States Grid Synchronisation","country":"立陶宛","region":"欧洲","cat":"grid","coord":[24.00,56.00],"cap":"三国电网脱俄并入欧洲同步网","inv":12,"invText":"约 12 亿美元（16 亿欧元）","status":"投运","year":2025,"updated":"2025-02","owner":"Litgrid / AST / Elering","flagship":true,"desc":"爱沙尼亚/拉脱维亚/立陶宛脱离俄电网并入欧洲。","detail":"2025 年 2 月,爱沙尼亚、拉脱维亚、立陶宛三国电网正式脱离俄罗斯-白俄'BRELL'同步区,经波兰并入欧洲大陆同步电网,涉及大量电网加固、调相机与控制改造,总投资约 16 亿欧元。这是欧盟能源安全与去俄化的标志性里程碑。","progress":"2025-02 完成脱俄并入欧洲同步网"},
  {"id":2726,"name":"东部绿色链路 4（苏格兰—英格兰 HVDC）","en":"Eastern Green Link 4","country":"英国","region":"欧洲","cat":"grid","coord":[-1.50,55.50],"cap":"2 GW HVDC 海缆","inv":30,"invText":"约 30 亿美元","status":"规划","year":2032,"updated":"2025-09","owner":"SSEN Transmission / National Grid","flagship":false,"desc":"把苏格兰风电送往英格兰的海底直流。","route":[[-1.8,57.5],[-0.2,53.2]],"detail":"由 SSEN 与 National Grid 合作开发的 2GW HVDC 海底电缆,把苏格兰东北部丰富的风电送往英格兰负荷中心,是英国'东部绿色链路'系列(EGL1/2 已推进)的延伸,2025 年推进审批与并网,目标 2030 年代初投运。","progress":"2025 年推进规划与审批"},

  // ===== 储能（2727-2731）=====
  {"id":2727,"name":"索普马什电池储能（英国）","en":"Thorpe Marsh BESS","country":"英国","region":"欧洲","cat":"storage","coord":[-1.05,53.60],"cap":"约 1.4 GW","inv":8,"invText":"约 8 亿美元","status":"在建","year":2027,"updated":"2025-10","owner":"FlexGen / SSE 等","flagship":true,"desc":"欧洲最大电池储能融资关闭项目之一。","detail":"位于英国南约克郡原燃煤电厂区,装机约 1.4GW,2025 年达成欧洲规模最大的电池储能项目融资关闭之一,复用既有并网点为英国电网提供大规模调频与移峰填谷,是英国电池储能创纪录年份的旗舰项目。","progress":"2025 年达成大额项目融资关闭,开工建设"},
  {"id":2728,"name":"林贝格 III 抽水蓄能（奥地利）","en":"Limberg III Pumped Storage","country":"奥地利","region":"欧洲","cat":"storage","coord":[12.70,47.25],"cap":"480 MW","inv":5,"invText":"约 5 亿美元","status":"投运","year":2025,"updated":"2025-09","owner":"Verbund","flagship":false,"desc":"奥地利卡普伦抽蓄群新增 480MW。","detail":"位于奥地利卡普伦(Kaprun),由 Verbund 投建,新增 480MW 抽水蓄能,使卡普伦机组群总装机达 1382MW、抽水能力 1120MW。历经四年建设于 2025 年 9 月投运,增强阿尔卑斯山区长时调节与可再生消纳能力。","progress":"2025-09 建成投运"},
  {"id":2729,"name":"里德尔抽水蓄能（德奥边境）","en":"Riedl Pumped Storage","country":"德国","region":"欧洲","cat":"storage","coord":[13.40,48.50],"cap":"约 300 MW","inv":5,"invText":"约 5 亿美元","status":"在建","year":2030,"updated":"2025-10","owner":"Donaukraft / Verbund","flagship":false,"desc":"多瑙河畔德奥边境新建抽水蓄能。","detail":"位于德国巴伐利亚帕绍附近、德奥边境多瑙河畔,规划约 300MW 抽水蓄能,2025 年 10 月在德奥两侧启动生态措施与施工准备,为德国南部提供长时储能与电网调节,缓解可再生波动。","progress":"2025-10 启动生态措施与施工准备"},
  {"id":2730,"name":"意大利 MACSE 长时储能容量（首拍）","en":"Italy MACSE Long-Duration Storage","country":"意大利","region":"欧洲","cat":"storage","coord":[15.00,40.50],"cap":"约 10 GWh（首拍）","inv":30,"invText":"约 30 亿美元","status":"规划","year":2028,"updated":"2025-09","owner":"Terna（MACSE 机制）","flagship":true,"desc":"意大利首个长时储能容量拍卖，10GWh 落南部。","detail":"意大利电网公司 Terna 主导的 MACSE 长时储能容量机制,2025 年 9 月完成首次拍卖,锁定约 10GWh 储能容量,主要布局在意大利南部可再生富集区。机制为长时电池/储能提供长期容量收入保障,撬动数十亿欧元投资,2028 年起陆续投运。","progress":"2025-09 首次拍卖落定约 10GWh"},
  {"id":2731,"name":"克鲁阿坎 2 号抽水蓄能（苏格兰）","en":"Cruachan 2 Pumped Storage","country":"英国","region":"欧洲","cat":"storage","coord":[-5.12,56.39],"cap":"600 MW","inv":8,"invText":"约 8 亿美元（逾 5 亿英镑）","status":"规划","year":2030,"updated":"2025-07","owner":"Drax","flagship":false,"desc":"苏格兰'空心山'抽蓄扩建 600MW。","detail":"位于苏格兰阿盖尔郡本克鲁阿坎山,Drax 在既有'空心山'抽水蓄能旁扩建 600MW 新机组,长时储能为英国电网提供调峰与惯量支撑。2025 年随英国长时储能(LDES)容量机制推进至投资决定阶段,目标 2030 年投运。","progress":"2025 年随 LDES 机制推进投资决定"},

  // ===== 工商业·配网大客户（电池/电解槽制造）（2732-2736）=====
  {"id":2732,"name":"亿纬锂能匈牙利电池厂","en":"EVE Energy Hungary Battery Plant","country":"匈牙利","region":"欧洲","cat":"ci","coord":[21.60,47.50],"cap":"28 GWh/年（圆柱电池）","inv":14,"invText":"约 14 亿美元（4000 亿福林）","status":"在建","year":2026,"updated":"2025-06","owner":"亿纬锂能（EVE Energy）","flagship":true,"desc":"匈牙利大圆柱电池厂，供宝马新世代。","detail":"位于匈牙利德布勒森,由中国亿纬锂能投建,年产能 28GWh 大圆柱电池,主供宝马'新世代(Neue Klasse)'车型。投资约 4000 亿福林(约 14 亿美元),2025 年 2 月下线首批电芯,计划 2026 年规模投产,是匈牙利电池产业集群的新成员。","progress":"2025-02 下线首批电芯,推进 2026 量产"},
  {"id":2733,"name":"远景 AESC 杜埃电池超级工厂（法国）","en":"Envision AESC Douai Gigafactory","country":"法国","region":"欧洲","cat":"ci","coord":[3.10,50.40],"cap":"一期 9-30 GWh/年","inv":14,"invText":"约 14 亿美元（20 亿欧元）","status":"在建","year":2026,"updated":"2025-09","owner":"远景动力（Envision AESC）","flagship":true,"desc":"法国杜埃电池超级工厂，供雷诺 Ampere。","detail":"位于法国北部杜埃,由远景动力投建,一期年产能约 9GWh、远期可扩至 30GWh+,主供雷诺电动车子公司 Ampere。是法国北部'电池谷'的核心工厂之一,投资约 20 亿欧元,2025 年推进产线投产爬坡。","progress":"2025 年产线投产爬坡"},
  {"id":2734,"name":"中创新航葡萄牙锂电池基地","en":"CALB Portugal Battery Base","country":"葡萄牙","region":"欧洲","cat":"ci","coord":[-8.60,40.60],"cap":"锂电池制造基地","inv":18,"invText":"约 18 亿美元","status":"规划","year":2028,"updated":"2026-01","owner":"中创新航（CALB）","flagship":false,"desc":"中创新航在葡萄牙新建锂电池基地。","detail":"2026 年 1 月中国中创新航(CALB)与葡萄牙政府签署投资协议,在葡萄牙建设锂电池生产基地,服务欧洲电动车与储能市场,是中国电池企业进一步布局欧洲、利用伊比利亚绿电与港口优势的代表项目。","progress":"2026-01 与葡政府签署投资协议"},
  {"id":2735,"name":"海辰储能西班牙储能电池厂","en":"Hithium Spain Battery/ESS Plant","country":"西班牙","region":"欧洲","cat":"ci","coord":[-3.70,40.40],"cap":"大型电池与储能系统制造","inv":4,"invText":"约 4 亿美元（4 亿欧元）","status":"规划","year":2028,"updated":"2026-03","owner":"海辰储能（Hithium）","flagship":false,"desc":"海辰储能在西班牙建大型储能电池厂。","detail":"2026 年 3 月中国海辰储能(Hithium)与西班牙政府签署意向书,拟投资约 4 亿欧元建设大型电池与储能系统(BESS)制造工厂,服务欧洲快速增长的网级储能市场,推动储能电池本地化制造。","progress":"2026-03 与西班牙政府签署投资意向"},
  {"id":2736,"name":"托普索 SOEC 电解槽工厂（丹麦）","en":"Topsoe SOEC Electrolyser Factory","country":"丹麦","region":"欧洲","cat":"ci","coord":[9.00,56.10],"cap":"固体氧化物电解槽 500 MW/年","inv":4,"invText":"约 4 亿美元","status":"投运","year":2025,"updated":"2025-06","owner":"Topsoe","flagship":false,"desc":"全球首座规模化 SOEC 电解槽工厂。","detail":"位于丹麦海宁,由 Topsoe 投建,是全球首座大规模固体氧化物电解槽(SOEC)制造工厂,首期年产能 500MW(可扩至 5GW),为欧洲绿氢/绿色燃料项目提供高效电解装备,2025 年投产,强化欧洲氢能装备供应链。","progress":"2025 年工厂投产"},

  // ===== 数据中心 / AI 算力（2737-2741）=====
  {"id":2737,"name":"英伟达-德国电信工业 AI 云","en":"NVIDIA–Deutsche Telekom Industrial AI Cloud","country":"德国","region":"欧洲","cat":"datacenter","coord":[11.58,48.14],"cap":"工业 AI 算力（万卡级 GPU）","inv":10,"invText":"约 10 亿美元","status":"在建","year":2026,"updated":"2026-01","owner":"NVIDIA / Deutsche Telekom","flagship":true,"desc":"全球首个工业 AI 云，赋能德国制造业。","detail":"由英伟达与德国电信合建,位于德国(慕尼黑等地),是全球首个'工业 AI 云',部署万卡级英伟达 GPU,为西门子等德国制造业提供 AI 算力,推动工业数字化与具身智能,2025 年宣布、2026 年投运,是欧洲主权 AI 算力的旗舰。","progress":"2026 年算力部署投运"},
  {"id":2738,"name":"英伟达英国 AI 基础设施","en":"NVIDIA UK AI Infrastructure","country":"英国","region":"欧洲","cat":"datacenter","coord":[-0.50,51.50],"cap":"下一代 AI 算力集群","inv":25,"invText":"约 25 亿美元（20 亿英镑+）","status":"在建","year":2027,"updated":"2025-09","owner":"NVIDIA / Nscale / CoreWeave / Microsoft","flagship":true,"desc":"英伟达联合伙伴在英国建大规模 AI 算力。","detail":"英伟达宣布投资 20 亿英镑布局英国 AI 市场,与 Nscale、CoreWeave、微软等合作建设英国下一代 AI 基础设施(Blackwell GPU 集群),支撑英国主权 AI 与生成式 AI 算力需求,2025-2027 年分阶段落地。","progress":"2025 年公布并启动算力部署"},
  {"id":2739,"name":"欧盟 AI 超级工厂计划","en":"EU AI Gigafactories Initiative","country":"欧盟","region":"欧洲","cat":"datacenter","coord":[10.00,50.00],"cap":"4-5 座 AI 超级工厂","inv":200,"invText":"约 200 亿美元（200 亿欧元）","status":"规划","year":2028,"updated":"2026-02","owner":"欧盟委员会 + 产业联合体","flagship":true,"desc":"欧盟 200 亿欧元建 4-5 座 AI 超级工厂。","detail":"欧盟委员会 2025 年提出投资 200 亿欧元在欧盟建设 4-5 座'AI 超级工厂(gigafactories)',作为撬动 2000 亿欧元 AI 投资的锚点。意向征集吸引 76 份申请、覆盖 16 国 60 个站点、拟投逾 2300 亿欧元,正式招标推迟至 2026 年初,旨在打造欧洲主权 AI 算力底座。","progress":"2026 年初推进正式招标与选址"},
  {"id":2740,"name":"谷歌德国数据中心与云投资","en":"Google Germany Data Centre Investment","country":"德国","region":"欧洲","cat":"datacenter","coord":[9.00,50.10],"cap":"多座数据中心 + 云区","inv":40,"invText":"约 40 亿美元（55 亿欧元）","status":"在建","year":2029,"updated":"2025-11","owner":"Google","flagship":false,"desc":"谷歌承诺至 2029 年大举投资德国数据中心。","detail":"谷歌宣布到 2029 年在德国投资约 55 亿欧元,新建/扩建数据中心(哈瑙等地)与云区,并配套可再生购电,服务德国及欧洲云与 AI 需求,是谷歌在欧洲规模最大的单国投资之一。","progress":"2025 年公布并推进数据中心建设"},
  {"id":2741,"name":"AWS 欧洲主权云（德国勃兰登堡）","en":"AWS European Sovereign Cloud","country":"德国","region":"欧洲","cat":"datacenter","coord":[13.40,52.40],"cap":"独立主权云区","inv":50,"invText":"约 50 亿美元（78 亿欧元）","status":"在建","year":2027,"updated":"2025-08","owner":"Amazon Web Services","flagship":true,"desc":"AWS 78 亿欧元建欧洲独立主权云。","detail":"亚马逊云科技投资约 78 亿欧元在德国勃兰登堡建设'欧洲主权云(European Sovereign Cloud)',数据与运营完全位于欧盟、由欧盟员工管理,满足政府与受监管行业的数据主权要求,首个区域 2025 年起建设、计划 2027 年前后投运。","progress":"2025 年建设推进,目标 2027 上线"},

  // ===== 大交通（高铁·机场·港口）（2742-2745）=====
  {"id":2742,"name":"波罗的海铁路（Rail Baltica）","en":"Rail Baltica High-Speed Rail","country":"立陶宛","region":"欧洲","cat":"transport","coord":[24.10,57.00],"cap":"约 870 公里高速铁路","inv":100,"invText":"约 100 亿美元（一期 153 亿欧元）","status":"在建","year":2030,"updated":"2025-06","owner":"RB Rail（爱沙尼亚/拉脱维亚/立陶宛）","flagship":true,"desc":"连接波罗的三国与波兰的欧标高铁。","route":[[24.75,59.44],[24.11,56.95],[23.90,54.90],[21.00,52.23]],"detail":"全长近 900 公里的欧洲标准轨高速铁路,纵贯爱沙尼亚、拉脱维亚、立陶宛并接入波兰、并入欧盟铁路网,一期预算约 153 亿欧元。2025 年波兰与波罗的各国大规模施工,塔林乌莱米斯特终端首站台投用,目标 2030 年完成一期,是波罗的国家与欧洲互联的旗舰工程。","progress":"2025 年多段施工,塔林首站台投用"},
  {"id":2743,"name":"大巴黎快线（法国）","en":"Grand Paris Express","country":"法国","region":"欧洲","cat":"transport","coord":[2.35,48.85],"cap":"约 200 公里自动化地铁（4 条新线）","inv":230,"invText":"约 230 亿美元（360 亿欧元）","status":"在建","year":2030,"updated":"2025-09","owner":"Société des Grands Projets","flagship":true,"desc":"欧洲最大轨交工程，巴黎 4 条新地铁环线。","detail":"环绕大巴黎的自动化地铁网络,新建约 200 公里线路(15/16/17/18 号线)与 68 座新站,总投资约 360 亿欧元,是欧洲规模最大的城市轨道工程。多段隧道掘进与车站建设推进,部分线路配合 2024 奥运后陆续开通,目标 2030 年前后建成主体。","progress":"2025 年多线段隧道与车站施工推进"},
  {"id":2744,"name":"巴斯克 Y 形高铁（西班牙）","en":"Basque Y High-Speed Rail","country":"西班牙","region":"欧洲","cat":"transport","coord":[-2.50,43.10],"cap":"连接三大巴斯克城市高铁","inv":45,"invText":"约 45 亿美元","status":"在建","year":2028,"updated":"2025-08","owner":"ADIF / 巴斯克政府","flagship":false,"desc":"连接毕尔巴鄂-圣塞-维多利亚的 Y 形高铁。","detail":"西班牙北部巴斯克地区'Y'形高速铁路,连接毕尔巴鄂、圣塞瓦斯蒂安与维多利亚三大城市,并接入西班牙高铁网与法国方向,是连通伊比利亚与欧洲大西洋走廊的关键段。2025 年多标段施工推进,目标 2028 年前后通车。","progress":"2025 年多标段施工推进"},
  {"id":2745,"name":"第三山口高铁（热那亚-米兰，意大利）","en":"Terzo Valico (Genoa–Milan HSR)","country":"意大利","region":"欧洲","cat":"transport","coord":[8.90,44.70],"cap":"约 53 公里高铁（含长隧道）","inv":50,"invText":"约 50 亿美元（68 亿欧元）","status":"在建","year":2027,"updated":"2025-09","owner":"RFI / 意大利铁路","flagship":false,"desc":"连接热那亚港与米兰的高铁与货运通道。","route":[[8.93,44.41],[8.93,44.92]],"detail":"意大利'第三山口(Terzo Valico dei Giovi)'高铁,连接热那亚港与米兰/都灵平原,含约 27 公里的吉奥维隧道,是连通地中海热那亚港与欧洲莱茵-阿尔卑斯走廊的客货两用通道,总投资约 68 亿欧元。2025 年隧道掘进推进,目标 2027 年通车。","progress":"2025 年隧道掘进推进"},

  // ===== 石油化工·油气·LNG（2746-2753）=====
  {"id":2746,"name":"约翰·卡斯特伯格油田（挪威）","en":"Johan Castberg Field","country":"挪威","region":"欧洲","cat":"petro","coord":[20.20,72.50],"cap":"22 万桶/日","inv":80,"invText":"约 80 亿美元（860 亿挪威克朗）","status":"投运","year":2025,"updated":"2025-08","owner":"Equinor / Vår Energi / Petoro","flagship":true,"desc":"巴伦支海最大油田，开启北极新油区。","detail":"位于挪威巴伦支海,由 Equinor(46.3%)牵头,含 Skrugard/Havis/Drivis 三个油田,以 FPSO 开发,峰值产能 22 万桶/日。2025 年 8 月实现首次产油,是巴伦支海规模最大的在产油田,开启挪威北极油气新纪元,强化挪威作为欧洲长期能源出口国地位。","progress":"2025-08 实现首次产油"},
  {"id":2747,"name":"伊格德拉西尔油气开发（挪威）","en":"Yggdrasil Field Development","country":"挪威","region":"欧洲","cat":"petro","coord":[2.50,58.50],"cap":"协调开发多个油气田","inv":100,"invText":"约 100 亿美元（1150 亿挪威克朗）","status":"在建","year":2027,"updated":"2025-07","owner":"Aker BP / Equinor / PGNiG","flagship":true,"desc":"北海大型协调开发，多田一体化。","detail":"位于挪威北海中部,由 Aker BP 牵头,把 Hugin、Munin、Fulla 等多个油气田协调一体化开发,总投资约 1150 亿挪威克朗,是挪威近年最大的海上油气开发集群之一。2025 年推进平台与海底设施建设,计划 2027 年前后投产。","progress":"2025 年平台与海底设施建设推进"},
  {"id":2748,"name":"施塔德 LNG 接收站（德国）","en":"Stade LNG Terminal","country":"德国","region":"欧洲","cat":"petro","coord":[9.50,53.60],"cap":"FSRU 约 3.7 Mtpa","inv":7,"invText":"约 7 亿美元","status":"在建","year":2026,"updated":"2025-09","owner":"Deutsche Energy Terminal / Hanseatic Energy Hub","flagship":false,"desc":"德国易北河畔 LNG 接收站，2026 投运。","detail":"位于德国易北河畔施塔德,采用浮式储存再气化装置(FSRU),再气化能力约 3.7Mtpa,是德国摆脱俄气、保障供应安全的 LNG 进口枢纽之一。调试推迟至 2026 年二季度,后续将衔接陆上固定接收站。","progress":"2025 年推进调试,目标 2026 二季度投运"},
  {"id":2749,"name":"格但斯克 LNG 接收站（波兰）","en":"Gdańsk LNG Terminal","country":"波兰","region":"欧洲","cat":"petro","coord":[18.70,54.40],"cap":"FSRU >6 bcm/年","inv":6,"invText":"约 6 亿美元","status":"在建","year":2028,"updated":"2025-08","owner":"Gaz-System","flagship":false,"desc":"波兰第二座 LNG 进口接收站，FSRU。","detail":"位于波兰格但斯克湾,采用 FSRU(储罐 17 万立方米),再气化能力超 60 亿立方米/年,是波兰继希维诺乌伊希切之后的第二座 LNG 进口终端。2025 年开工,计划 2028 年初投运,强化波兰及中东欧的天然气供应安全与去俄化。","progress":"2025 年开工建设,目标 2028 投运"},
  {"id":2750,"name":"狄奥里加 LNG 接收站（希腊）","en":"Dioriga Gas FSRU (Greece)","country":"希腊","region":"欧洲","cat":"petro","coord":[23.00,38.00],"cap":"FSRU 进口再气化","inv":3,"invText":"约 3 亿美元","status":"在建","year":2026,"updated":"2025-06","owner":"Motor Oil Hellas","flagship":false,"desc":"希腊科林斯湾 LNG 进口接收站。","detail":"位于希腊科林斯湾,由 Motor Oil Hellas 开发的 FSRU LNG 进口接收站,2025 年初获批,计划 2026 年投运,是希腊打造'巴尔干 LNG 走廊'、向东南欧供气的组成部分。","progress":"2025 年获批,目标 2026 投运"},
  {"id":2751,"name":"色雷斯 LNG 接收站（希腊）","en":"Thrace FSRU (Greece)","country":"希腊","region":"欧洲","cat":"petro","coord":[25.50,40.90],"cap":"约 6 bcm/年","inv":5,"invText":"约 5 亿美元（约 6 亿欧元）","status":"规划","year":2028,"updated":"2026-01","owner":"希腊 LNG 开发方","flagship":false,"desc":"希腊北部新增 LNG 接收能力 6bcm。","detail":"位于希腊北部色雷斯地区,规划再气化能力约 6bcm/年,2026 年 1 月获环境批准,因约 6 亿欧元造价需欧盟金融工具或国家资金支持。建成后(目标 2028)进一步增强希腊向巴尔干与中东欧供气的'LNG 走廊'能力。","progress":"2026-01 获环境批准,推进融资"},
  {"id":2752,"name":"拉文纳 LNG 接收站（意大利）","en":"Ravenna FSRU (Italy)","country":"意大利","region":"欧洲","cat":"petro","coord":[12.30,44.40],"cap":"FSRU 约 5 bcm/年","inv":3,"invText":"约 3 亿美元","status":"投运","year":2025,"updated":"2025-06","owner":"Snam","flagship":false,"desc":"意大利亚得里亚海 LNG 进口接收站。","detail":"位于意大利亚得里亚海拉文纳近海,由 Snam 运营的 FSRU(BW Singapore),再气化能力约 5bcm/年,2025 年投运,增强意大利去俄气后的天然气供应弹性,是意大利新增 LNG 进口能力的组成部分。","progress":"2025 年投运并接气"},
  {"id":2753,"name":"海王星深水气田（罗马尼亚黑海）","en":"Neptun Deep Gas (Black Sea)","country":"罗马尼亚","region":"欧洲","cat":"petro","coord":[29.50,44.00],"cap":"约 100 亿立方米/年","inv":40,"invText":"约 40 亿美元","status":"在建","year":2027,"updated":"2025-09","owner":"OMV Petrom / Romgaz","flagship":true,"desc":"黑海最大天然气开发，欧盟新增大气源。","detail":"位于罗马尼亚黑海专属经济区深水区,由 OMV Petrom 与 Romgaz 合资开发,可采储量约 1000 亿立方米,峰值年产约 100 亿立方米,总投资约 40 亿欧元。是黑海规模最大的天然气开发,建成后将使罗马尼亚成为欧盟最大天然气生产国之一,2025 年推进海上钻完井,计划 2027 年投产。","progress":"2025 年海上钻井与平台建设推进"},

  // ===== 矿业·关键原材料（2754-2761）=====
  {"id":2754,"name":"凯利伯锂矿与氢氧化锂厂（芬兰）","en":"Keliber Lithium Project","country":"芬兰","region":"欧洲","cat":"mining","coord":[23.50,63.60],"cap":"电池级氢氧化锂约 1.5 万吨/年","inv":8,"invText":"约 8 亿美元","status":"在建","year":2026,"updated":"2025-09","owner":"Sibanye-Stillwater / 芬兰矿产","flagship":true,"desc":"欧洲首个矿-精炼一体化锂项目。","detail":"位于芬兰中部,由 Sibanye-Stillwater 控股,是欧洲首个将锂矿开采与氢氧化锂精炼整合于同一价值链的项目。锂辉石矿(Syväjärvi 等)配套科科拉氢氧化锂厂,规划电池级氢氧化锂约 1.5 万吨/年,是欧盟 CRMA 战略项目,2025 年建设推进,服务欧洲电池供应链。","progress":"2025 年矿山与精炼厂建设推进"},
  {"id":2755,"name":"火山零碳锂项目（德国上莱茵）","en":"Vulcan Zero Carbon Lithium","country":"德国","region":"欧洲","cat":"mining","coord":[8.40,49.20],"cap":"电池级氢氧化锂约 2.4 万吨/年","inv":15,"invText":"约 15 亿美元","status":"在建","year":2027,"updated":"2025-08","owner":"Vulcan Energy","flagship":true,"desc":"地热卤水提锂，零碳供应欧洲车企。","detail":"位于德国上莱茵地堑,Vulcan Energy 利用地热卤水直接提锂(DLE)并副产地热能,实现近零碳锂生产,规划电池级氢氧化锂约 2.4 万吨/年,已与 Stellantis、大众、雷诺等签包销协议。一期 Lionheart 项目推进建设,是欧盟 CRMA 战略项目与欧洲本土锂供应的标杆。","progress":"2025 年一期建设推进,中央锂厂启动"},
  {"id":2756,"name":"萨凡纳巴罗佐锂矿（葡萄牙）","en":"Savannah Barroso Lithium","country":"葡萄牙","region":"欧洲","cat":"mining","coord":[-7.80,41.80],"cap":"锂辉石精矿","inv":6,"invText":"约 6 亿美元","status":"规划","year":2028,"updated":"2025-07","owner":"Savannah Resources","flagship":false,"desc":"西欧最大硬岩锂矿，葡萄牙北部。","detail":"位于葡萄牙北部巴罗佐(Barroso),由 Savannah Resources 开发,是西欧规模最大的硬岩(锂辉石)锂矿,规划年产锂精矿供应欧洲电池供应链。作为欧盟 CRMA 战略项目,2025 年推进环境许可与社区协商,目标 2028 年前后投产。","progress":"2025 年推进环境许可与开发"},
  {"id":2757,"name":"沃尔夫斯贝格锂矿（奥地利）","en":"Wolfsberg Lithium Project","country":"奥地利","region":"欧洲","cat":"mining","coord":[14.80,46.80],"cap":"电池级锂","inv":4,"invText":"约 4 亿美元","status":"规划","year":2028,"updated":"2025-06","owner":"European Lithium","flagship":false,"desc":"中欧首个在建硬岩锂矿之一。","detail":"位于奥地利克恩顿州沃尔夫斯贝格,由 European Lithium 开发,是中欧首批推进的硬岩锂矿之一,规划地下开采并配套精炼生产电池级锂。作为欧盟关键原材料本地化的组成部分,2025 年推进可研与融资,目标 2028 年前后投产。","progress":"2025 年推进可研与融资"},
  {"id":2758,"name":"LKAB 佩尔盖耶稀土项目（瑞典基律纳）","en":"LKAB Per Geijer Rare Earths (Kiruna)","country":"瑞典","region":"欧洲","cat":"mining","coord":[20.20,67.85],"cap":"欧洲最大稀土矿床","inv":12,"invText":"约 12 亿美元","status":"规划","year":2030,"updated":"2025-10","owner":"LKAB","flagship":true,"desc":"欧洲已知最大稀土矿床，基律纳。","detail":"位于瑞典北部基律纳,LKAB 在佩尔盖耶(Per Geijer)发现欧洲已知规模最大的稀土氧化物矿床(逾 130 万吨 REO),伴生磷与铁。规划随铁矿开采共采稀土并配套分离,对摆脱欧洲对华稀土依赖意义重大,2025 年推进许可,目标 2030 年代投产。","progress":"2025 年推进采矿许可与开发"},
  {"id":2759,"name":"伊梅里斯 EMILI 锂矿（法国）","en":"Imerys EMILI Lithium Project","country":"法国","region":"欧洲","cat":"mining","coord":[3.30,46.30],"cap":"电池级氢氧化锂约 3.4 万吨/年","inv":10,"invText":"约 10 亿美元（10 亿欧元）","status":"规划","year":2028,"updated":"2025-08","owner":"Imerys","flagship":false,"desc":"法国最大锂项目，年供 70 万辆电车。","detail":"位于法国中部阿列省,由 Imerys 开发,规划地下云母锂矿配套氢氧化锂厂,年产电池级氢氧化锂约 3.4 万吨,可供约 70 万辆电动车。作为法国 CRMA 战略项目与欧洲本土锂供应支柱,2025 年推进公众辩论与许可,目标 2028 年投产。","progress":"2025 年推进许可与公众协商"},
  {"id":2760,"name":"艾蒂克铜矿扩建（瑞典）","en":"Aitik Copper Mine Expansion","country":"瑞典","region":"欧洲","cat":"mining","coord":[20.95,67.07],"cap":"瑞典最大铜矿，扩产","inv":6,"invText":"约 6 亿美元","status":"在建","year":2027,"updated":"2025-07","owner":"Boliden","flagship":false,"desc":"瑞典最大铜矿扩产，供欧洲电气化。","detail":"位于瑞典北部耶利瓦勒,由 Boliden 运营,是瑞典最大的铜矿,通过扩建选矿与延深开采提升铜及副产金银产量,服务欧洲电气化与电网铜需求,2025 年推进扩产投资,是欧洲本土基础金属供应的支柱矿山。","progress":"2025 年扩产投资与工程推进"},
  {"id":2761,"name":"萨卡蒂铜镍钴矿（芬兰）","en":"Sakatti Cu-Ni-PGM Project","country":"芬兰","region":"欧洲","cat":"mining","coord":[27.00,67.90],"cap":"铜镍钴+铂族金属","inv":8,"invText":"约 8 亿美元","status":"规划","year":2030,"updated":"2025-09","owner":"Anglo American","flagship":false,"desc":"芬兰高品位铜镍钴矿，电池金属新源。","detail":"位于芬兰北部索丹屈莱,由英美资源(Anglo American)开发,是欧洲高品位铜-镍-钴及铂族金属矿床,采用低扰动地下开采。作为欧盟关键原材料本地化的重要电池/电气化金属来源,2025 年推进许可与可研,目标 2030 年代投产。","progress":"2025 年推进环境许可与可研"},

  // ===== 国际大客户（中国出海龙头在欧项目）（2762-2763）=====
  {"id":2762,"name":"中国电建克罗地亚塞尼风电","en":"PowerChina Senj Wind Farm (Croatia)","country":"克罗地亚","region":"欧洲","cat":"client","coord":[14.90,45.00],"cap":"约 156 MW 及二期","inv":2,"invText":"约 2 亿美元","status":"投运","year":2024,"updated":"2025-06","owner":"中国电建","flagship":false,"desc":"中国电建在克罗地亚的风电 EPC 与运营。","detail":"中国电建在克罗地亚塞尼(Senj)地区承建并参与运营的风电项目,装机约 156MW,是中国企业在中东欧落地的代表性新能源 EPC 项目,后续推进二期扩建,助力克罗地亚能源转型与欧盟可再生目标。","progress":"一期投运,2025 年推进二期扩建"},
  {"id":2763,"name":"三峡欧洲德国梅尔温德海上风电运营","en":"CTG Europe Meerwind Offshore (Germany)","country":"德国","region":"欧洲","cat":"client","coord":[7.70,54.40],"cap":"288 MW 海上风电","inv":3,"invText":"约 3 亿美元","status":"投运","year":2025,"updated":"2025-06","owner":"三峡欧洲","flagship":false,"desc":"三峡欧洲持有运营的德国北海海上风电。","detail":"三峡集团通过三峡欧洲持有并运营位于德国北海的梅尔温德(Meerwind Süd/Ost)海上风电场,装机 288MW,是中国企业在欧洲海上风电运营的代表资产,稳定向德国电网供应清洁电力,体现三峡国际化清洁能源布局。","progress":"2025 年稳定运营,贡献清洁电力"}
]);
