// 澳洲（大洋洲）专项 —— 2026-06 第十四轮深挖
// 覆盖澳大利亚为主、兼顾新西兰/巴布亚新几内亚，近一年(2025中-2026中)已开工投运
// + 未来5年(到2030/2031)规划/在建。8 大品类全覆盖。
// region 一律 '大洋洲'；coord 为 [经度,纬度] WGS-84；concat 进 ENERGY_EXTRA；
// index.html 在 data-africa.js 之后、progress.js 之前加载。id 段 2600-2682。
window.ENERGY_EXTRA = (window.ENERGY_EXTRA || []).concat([
  // ===== 可再生能源发电（2600-2616）=====
  {"id":2600,"name":"上卡利奥普光伏电站（力拓供电）","en":"Upper Calliope Solar Farm","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[151.25,-23.92],"cap":"1.1 GW","inv":10,"invText":"约 10 亿美元","status":"规划","year":2026,"updated":"2025-12","owner":"European Energy","flagship":true,"desc":"昆士兰格拉德斯通 1.1GW 光伏，供力拓铝业。","detail":"丹麦 European Energy 在昆州中部格拉德斯通附近开发的 1.1GW 大型光伏电站，2025 年 12 月获得开发许可，计划 2026 年开工。项目与力拓(Rio Tinto)签署 25 年购电协议，所发电力供应其昆州博因岛铝冶炼与亚文(Yarwun)氧化铝等高载能工业，是澳洲单体规模最大的在建光伏之一。","progress":"2025-12 获开发审批，2026 年拟开工"},
  {"id":2601,"name":"金原野风电场（一二期）","en":"Golden Plains Wind Farm","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[143.70,-37.90],"cap":"1.33 GW（756+577MW）","inv":26,"invText":"约 26 亿美元（40 亿澳元）","status":"在建","year":2025,"updated":"2026-01","owner":"TagEnergy / WestWind","flagship":true,"desc":"南半球最大风电场，维州 1.33GW 两期建设。","detail":"位于维多利亚州罗克伍德附近，分两期共装机 1.33GW，是南半球在建规模最大的陆上风电场。一期 756MW（122 台风机）于 2025 年一季度起陆续投产；二期 577MW 已于 2025 年获非追索贷款（含 CEFC）实现融资关闭并开工，计划 2027 年中投运，并配套 150MW/600MWh 电池储能。","progress":"2026-01 一期投产、二期开工建设中"},
  {"id":2602,"name":"利物浦山脉风电场","en":"Liverpool Range Wind Farm","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[149.95,-31.78],"cap":"1.3 GW","inv":25,"invText":"约 25 亿美元","status":"规划","year":2027,"updated":"2025-10","owner":"Tilt Renewables","flagship":true,"desc":"新州中西部 1.3GW 风电，可供 73 万户。","detail":"位于新南威尔士州中西部库拉(Coolah)以东约 130 公里，2025 年获新州政府批准扩容修改，最大发电容量增至 1.3GW，可满足约 73 万户家庭用电，是新州审批容量最大的陆上风电项目之一，将接入新英格兰可再生能源区(REZ)外送通道。","progress":"2025-10 获扩容修改批准，推进至开工准备"},
  {"id":2603,"name":"良缘绿氢绿氨枢纽（GEGHA·穆里）","en":"Good Earth Green Hydrogen & Ammonia (GEGHA)","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[149.84,-29.46],"cap":"绿氨 4500 吨/年 + 绿氢 200 吨/年","inv":5,"invText":"约 5 亿美元","status":"在建","year":2027,"updated":"2025-07","owner":"Good Earth Green Hydrogen and Ammonia","flagship":false,"desc":"新州穆里绿氢绿氨枢纽，2025-07 作出 FID。","detail":"位于新南威尔士州新英格兰地区穆里(Moree)附近，年产低碳氨 4500 吨、可再生氢 200 吨，2025 年 7 月达成最终投资决定并开工建设，计划 2027 年投产，是澳洲东部首批落地的绿氢绿氨一体化示范项目之一。","progress":"2025-07 完成 FID 并开工，目标 2027 投产"},
  {"id":2604,"name":"盟绿氨北领地绿氢绿氨项目","en":"Allied Green Ammonia (Gove, NT)","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[136.80,-12.25],"cap":"3 GW 电解 / 绿氨 95.85 万吨/年","inv":50,"invText":"约 50 亿美元","status":"规划","year":2028,"updated":"2025-06","owner":"Allied Green Ammonia","flagship":true,"desc":"北领地戈夫 3GW 电解绿氨，配 4.75GW 光储。","detail":"位于北领地戈夫(Gove)半岛，规划 3GW 电解槽、年产绿氨约 95.85 万吨，配套 4.75GW 光伏与日均 1.6GWh 电池储能。2025 年与 ABB 签署工程设计协议，加速推进 FID，主要面向亚洲出口绿氨，是澳洲北部规模最大的绿氢绿氨规划之一。","progress":"2025 年签 ABB 工程协议，加速推进 FID"},
  {"id":2605,"name":"福特斯库皮尔巴拉离网光储风一体化","en":"Fortescue Pilbara Off-grid Renewable Network","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[119.70,-22.40],"cap":"光伏约 600MW + 风电 600MW + 储能 5.4GWh","inv":20,"invText":"约 20 亿美元","status":"在建","year":2026,"updated":"2026-02","owner":"Fortescue（比亚迪/远景供货）","flagship":true,"desc":"全球最大离网可再生能源网络，为铁矿供电脱碳。","detail":"福特斯库在西澳皮尔巴拉铁矿区建设的离网清洁能源网络，含约百万块光伏组件(约 600MW)、600MW 风电与 5.4GWh 电池储能，电池由比亚迪供货、风机由远景能源供货，用于替代采矿柴油与天然气、实现 2030 年陆地业务净零。是全球规模最大的离网可再生能源系统，2025-2026 年陆续破土动工。","progress":"2026-02 多站点开工建设，分阶段并网"},
  {"id":2606,"name":"新英格兰光伏储能电站","en":"New England Solar Farm & BESS","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[151.50,-30.62],"cap":"720 MW 光伏 + 储能","inv":8,"invText":"约 8 亿美元","status":"投运","year":2025,"updated":"2025-06","owner":"ACEN Australia","flagship":false,"desc":"新州最大光伏之一，配套大型电池。","detail":"位于新南威尔士州乌拉拉(Uralla)附近，由菲律宾 ACEN 开发，光伏装机 720MW，是新州已投运规模最大的光伏电站之一，并配套大型电池储能。项目接入新英格兰可再生能源区(REZ)，为新州能源转型骨干电源。","progress":"2025 年全容量并网并配套储能投运"},
  {"id":2607,"name":"南方之星海上风电","en":"Star of the South Offshore Wind","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[146.90,-38.85],"cap":"最高 2.2 GW","inv":90,"invText":"约 90 亿美元","status":"规划","year":2031,"updated":"2025-09","owner":"Star of the South（Copenhagen Infrastructure Partners 等）","flagship":true,"desc":"澳洲最先进海上风电，吉普斯兰外海 2.2GW。","detail":"位于维多利亚州吉普斯兰外海，是澳大利亚进展最快的海上风电项目，最高装机 2.2GW，可供约 120 万户家庭用电。已持有可行性许可并推进环评与并网设计，作为吉普斯兰首批海上风电领跑者，目标 2030 年代初向电网送电。","progress":"2025 年推进可研许可与环评，目标 2030s 初投产"},
  {"id":2608,"name":"猎人海上风电（诺瓦卡斯特里安）","en":"Novocastrian Wind (Hunter Offshore)","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[152.30,-33.05],"cap":"约 2 GW","inv":80,"invText":"约 80 亿美元","status":"规划","year":2032,"updated":"2025-08","owner":"Novocastrian Wind","flagship":true,"desc":"新州猎人区首个海上风电可行性许可项目。","detail":"位于新南威尔士州纽卡斯尔外海猎人(Hunter)宣布海上风电区，2025 年 2 月获授可行性许可，规划装机约 2GW。开发方就商业安排申请延长开发期，作为猎人区域首个海上风电先导项目，配合当地燃煤电厂退役与产业脱碳。","progress":"2025 年获可行性许可，推进商业与并网安排"},
  {"id":2609,"name":"布利溪光伏储能综合体","en":"Bulli Creek Solar & Battery","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[151.30,-28.05],"cap":"2.5 GW 光伏（一期 300MW+425MW/1700MWh 电池）","inv":30,"invText":"约 30 亿美元","status":"规划","year":2028,"updated":"2025-11","owner":"Genex Power","flagship":true,"desc":"昆士兰 2.5GW 光储巨擘，分期开发。","detail":"位于昆士兰州米尔默兰(Millmerran)附近，规划光伏总装机 2.5GW，一期采用 300MW 光伏 + 425MW/1700MWh 电池组合以应对中午光伏过剩(光伏鸭形曲线)。融资关闭与开工调整至 2028 年，是昆州规模最大的光储一体化规划之一。","progress":"2025-11 一期方案调整，FID 与开工预计 2028"},
  {"id":2610,"name":"戈伊德南风光储基地","en":"Goyder South Wind/Solar/Battery","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[138.90,-33.70],"cap":"风电 1.2GW + 光伏 + 储能","inv":18,"invText":"约 18 亿美元","status":"在建","year":2026,"updated":"2025-07","owner":"Neoen","flagship":true,"desc":"南澳布拉风光储一体化大基地。","detail":"位于南澳州布拉(Burra)附近，由法国 Neoen 开发，规划风电约 1.2GW 并配套光伏与大型电池储能。一期风电已投产，后续分期推进，是南澳支撑高比例可再生、保障电网稳定的旗舰风光储基地，部分电力服务远期绿氢需求。","progress":"2025 年一期投产，后续分期在建"},
  {"id":2611,"name":"克拉克溪风光储混合电站","en":"Clarke Creek Wind/Solar/Battery","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[149.35,-22.80],"cap":"风电约 1GW + 光伏 + 储能","inv":16,"invText":"约 16 亿美元","status":"在建","year":2026,"updated":"2025-09","owner":"Squadron Energy","flagship":true,"desc":"昆士兰最大风光储混合能源枢纽之一。","detail":"位于昆士兰州中部克拉克溪，由 Squadron Energy(福雷斯特旗下)开发，规划风电约 1GW，并配套光伏与电池储能，分阶段建设。一期风电已并网，是昆州装机最大的风光储混合枢纽之一，支撑州内燃煤退役后的可再生供应。","progress":"2025 年一期风电并网，后续扩建在建"},
  {"id":2612,"name":"麦金太尔风电场","en":"MacIntyre Wind Farm","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[151.30,-28.25],"cap":"1.026 GW","inv":13,"invText":"约 13 亿美元（20 亿澳元）","status":"投运","year":2025,"updated":"2025-11","owner":"Acciona Energía","flagship":true,"desc":"南半球最大陆上风电场之一，162 台风机。","detail":"位于昆士兰州卡拉拉(Karara)附近，由西班牙 Acciona 开发，装机 1.026GW、共 162 台 6.2MW 风机，是南半球已投运规模最大的陆上风电场之一。2025 年陆续并网投运，电力部分供应昆州政府与大型工商业用户。","progress":"2025 年风机陆续并网，迈向全容量投运"},
  {"id":2613,"name":"陶哈拉地热电站（新西兰）","en":"Tauhara Geothermal Power Station","country":"新西兰","region":"大洋洲","cat":"renewable","coord":[176.10,-38.72],"cap":"174 MW","inv":5,"invText":"约 5 亿美元（9 亿纽元）","status":"投运","year":2024,"updated":"2025-06","owner":"Contact Energy","flagship":true,"desc":"新西兰近年最大地热电站，陶波湖畔。","detail":"位于新西兰北岛陶波(Taupo)附近，由 Contact Energy 投建，装机 174MW，是新西兰近年投产规模最大的地热电站，2024 年投运后显著提升北岛'稳定可再生'基荷能力，支撑新西兰迈向 100% 可再生电力。","progress":"2024 年投运，2025 年稳定满发运行"},
  {"id":2614,"name":"哈拉帕基风电场（新西兰）","en":"Harapaki Wind Farm","country":"新西兰","region":"大洋洲","cat":"renewable","coord":[176.62,-39.22],"cap":"176 MW","inv":2.5,"invText":"约 2.5 亿美元（4.5 亿纽元）","status":"投运","year":2024,"updated":"2025-06","owner":"Meridian Energy","flagship":false,"desc":"新西兰第二大风电场，霍克斯湾 41 台风机。","detail":"位于新西兰北岛霍克斯湾(Hawke's Bay)，由 Meridian Energy 投建，装机 176MW、共 41 台风机，是新西兰已投运第二大风电场，2024 年起陆续并网，进一步充实北岛可再生电源结构。","progress":"2024 年全容量投运并网"},
  {"id":2615,"name":"洛德斯通光伏电站群（新西兰）","en":"Lodestone Solar Farms","country":"新西兰","region":"大洋洲","cat":"renewable","coord":[173.30,-35.12],"cap":"多站合计逾 220 MW","inv":2,"invText":"约 2 亿美元","status":"在建","year":2026,"updated":"2025-10","owner":"Lodestone Energy","flagship":false,"desc":"新西兰最大公用事业光伏开发商，多站布局。","detail":"由 Lodestone Energy 在新西兰北部(凯塔亚 Kohirā 等)开发的公用事业级光伏电站群，多站合计装机逾 220MW，是新西兰规模最大的网级光伏组合。各站 2024-2026 年陆续投产，推动新西兰太阳能装机一年增长逾 70%。","progress":"2025 年多站投产，后续站点持续建设"},
  {"id":2616,"name":"昆士兰阿尔多加红土光伏（扩建段）","en":"Aldoga Renewable Hub Expansion","country":"澳大利亚","region":"大洋洲","cat":"renewable","coord":[151.10,-23.85],"cap":"扩建约 1.1 GW 光伏","inv":9,"invText":"约 9 亿美元","status":"规划","year":2027,"updated":"2025-12","owner":"European Energy / Acen 等","flagship":false,"desc":"格拉德斯通工业区光伏集群扩建，供绿色工业。","detail":"格拉德斯通州立开发区(Gladstone SDA)红土地带的光伏集群扩建段，规划新增约 1.1GW 光伏，服务当地氧化铝、铝冶炼与未来绿氢绿氨负荷。作为昆州'绿色工业重镇'的配套电源，2025 年底推进审批与购电协议。","progress":"2025-12 推进审批与工业购电协议"},

  // ===== 输变电·电网（2617-2624）=====
  {"id":2617,"name":"铜线计划输电工程（CopperString 2032）","en":"CopperString 2032 Transmission","country":"澳大利亚","region":"大洋洲","cat":"grid","coord":[142.50,-20.70],"cap":"840+ 公里 / 接入北昆资源区","inv":33,"invText":"约 33 亿美元（50 亿澳元）","status":"在建","year":2029,"updated":"2026-06","owner":"Powerlink Queensland","flagship":true,"desc":"北昆士兰 840 公里大动脉，连汤斯维尔—芒特艾萨。","route":[[146.82,-19.26],[139.49,-20.73]],"detail":"由 Powerlink 投建，初期建设从汤斯维尔至芒特艾萨约 840 公里新输电线路，接入北昆士兰矿业与新能源走廊，是澳洲规模最大的电网新建工程之一。东段计划 2032 年前建成，2025 年 12 月弗林德斯变电站(2.25 亿澳元)获基础设施批复推进开工。","progress":"2025年10月昆州《能源路线图》确认续建并控制成本（总投资逼近120亿澳元）：东段由500kV回调至330kV节省21亿澳元；2025年12月弗林德斯变电站（2.25亿澳元）获基础设施指定批准，2026年开工；休恩登营地2025年11月建成。"},
  {"id":2618,"name":"中西部奥拉纳可再生能源区输电（ACEREZ）","en":"Central-West Orana REZ Transmission","country":"澳大利亚","region":"大洋洲","cat":"grid","coord":[148.90,-32.00],"cap":"约 240 公里 500kV / 接入 4.5GW","inv":21,"invText":"约 21 亿美元（32 亿澳元）","status":"在建","year":2028,"updated":"2025-08","owner":"ACEREZ（ACCIONA/COBRA/Endeavour）","flagship":true,"desc":"新州首个可再生能源区配套输电网。","detail":"为新南威尔士州首个可再生能源区——中西部奥拉纳(Central-West Orana)区配套的高压输电网络，约 240 公里 500kV 线路与配套变电站，可接入约 4.5GW 风光储新能源。由 ACEREZ 联合体设计建设运营，2025 年起施工，计划 2028 年建成，是新州能源路线图的骨干工程。","progress":"2025 年主体施工，目标 2028 建成投运"},
  {"id":2619,"name":"猎人输电工程","en":"Hunter Transmission Project","country":"澳大利亚","region":"大洋洲","cat":"grid","coord":[151.30,-32.70],"cap":"约 120 公里 500kV","inv":6,"invText":"约 6 亿美元（9 亿澳元）","status":"规划","year":2029,"updated":"2025-09","owner":"Transgrid","flagship":false,"desc":"连接猎人区与中海岸的 500kV 新通道。","detail":"由 Transgrid 开发的新南威尔士州猎人地区 500kV 输电新通道，约 120 公里，强化猎人—中海岸—悉尼电网联系，支撑燃煤退役后可再生电力送往负荷中心，并接入猎人海上风电与离岸新能源。","progress":"2025 年推进环评与路径设计"},
  {"id":2620,"name":"西部可再生能源链路（维州）","en":"Western Renewables Link","country":"澳大利亚","region":"大洋洲","cat":"grid","coord":[143.40,-37.30],"cap":"约 190 公里 500kV","inv":20,"invText":"约 20 亿美元（30 亿澳元）","status":"规划","year":2029,"updated":"2025-10","owner":"AusNet Services","flagship":true,"desc":"维州西部 500kV 大动脉，接入西部风光。","detail":"由 AusNet 开发的维多利亚州西部 500kV 输电工程，约 190 公里，连接布尔加纳(Bulgana)—巴拉腊特—墨尔本西北，接入维州西部大量风光新能源并衔接 VNI West 跨州联络，是维州 2035 年 95% 可再生目标的关键通道。","progress":"2025 年推进审批与社区协商"},
  {"id":2621,"name":"新英格兰可再生能源区输电","en":"New England REZ Transmission","country":"澳大利亚","region":"大洋洲","cat":"grid","coord":[151.60,-30.50],"cap":"接入约 8GW 新能源","inv":20,"invText":"约 20 亿美元","status":"规划","year":2030,"updated":"2025-09","owner":"EnergyCo NSW / ACEREZ","flagship":false,"desc":"新州最大 REZ，规划接入约 8GW 风光储。","detail":"新南威尔士州新英格兰可再生能源区(REZ)的配套输电网络，规划接入约 8GW 风光储新能源，是新州五大 REZ 中容量最大者。2025 年福雷斯特等大型风光储项目获该区电网接入权，配套高压网络陆续推进设计与建设。","progress":"2025 年授予多项目接入权，网络推进设计"},
  {"id":2622,"name":"悉尼环网与电压支撑工程","en":"Sydney Ring (Powering Sydney's Future)","country":"澳大利亚","region":"大洋洲","cat":"grid","coord":[151.00,-33.83],"cap":"330kV 城市加强环网","inv":8,"invText":"约 8 亿美元","status":"在建","year":2027,"updated":"2025-07","owner":"Transgrid / Ausgrid","flagship":false,"desc":"加强大悉尼供电安全与可再生接入。","detail":"通过新建/升级城市 330kV 环网与电缆，强化大悉尼地区供电安全，应对利德尔、埃拉灵等燃煤退役后的供电缺口，并便利可再生电力进入负荷中心，是新州城市电网现代化的关键环。","progress":"2025 年分段施工推进"},
  {"id":2623,"name":"昆士兰超级电网骨干强化","en":"Queensland SuperGrid Backbone","country":"澳大利亚","region":"大洋洲","cat":"grid","coord":[146.50,-21.50],"cap":"多段 500/275kV 走廊","inv":13,"invText":"约 13 亿美元","status":"规划","year":2030,"updated":"2025-08","owner":"Powerlink Queensland","flagship":false,"desc":"昆士兰能源转型计划骨干输电网。","detail":"昆士兰州'能源与就业计划(SuperGrid)'框架下的骨干输电强化，沿海岸与内陆建设多段 500/275kV 走廊，连接北/中/南昆可再生能源区、抽蓄与海上风电，支撑州内大规模燃煤退役与新能源接入。","progress":"2025 年分项目推进规划与审批"},
  {"id":2624,"name":"新西兰北岛电网与库克海峡直流升级","en":"Transpower NZ Grid & HVDC Upgrade","country":"新西兰","region":"大洋洲","cat":"grid","coord":[174.80,-41.20],"cap":"北岛 220kV 强化 + HVDC 升级","inv":6,"invText":"约 6 亿美元（10 亿纽元）","status":"规划","year":2030,"updated":"2025-11","owner":"Transpower","flagship":false,"desc":"强化新西兰南北岛互联与上北岛供电。","detail":"新西兰国家电网公司 Transpower 推进的电网强化计划，包括上北岛(奥克兰/怀卡托)220kV 加强与连接南北岛的库克海峡 HVDC 升级，以接纳快速增长的光伏、风电与电池储能，保障北岛长期供电充裕。","progress":"2025 年发布投资计划，推进监管审批"},

  // ===== 储能（2625-2633）=====
  {"id":2625,"name":"奥拉纳电池储能（阿凯莎）","en":"Orana Battery Energy Storage System","country":"澳大利亚","region":"大洋洲","cat":"storage","coord":[148.92,-32.50],"cap":"415 MW / 1660 MWh（4 小时）","inv":4.3,"invText":"约 4.3 亿美元","status":"在建","year":2026,"updated":"2025-09","owner":"Akaysha Energy","flagship":true,"desc":"新州中西部奥拉纳 415MW/1660MWh 四小时电池。","detail":"位于新南威尔士州惠灵顿(Wellington)东北、中西部奥拉纳可再生能源区内，由 Akaysha Energy 开发，装机 415MW/1660MWh，可持续放电 4 小时。2025 年开工建设，是新州能源区配套的旗舰大型电池储能，提供调频与移峰填谷服务。","progress":"2025 年开工建设，推进至 2026 投运"},
  {"id":2626,"name":"博伦巴抽水蓄能","en":"Borumba Pumped Hydro","country":"澳大利亚","region":"大洋洲","cat":"storage","coord":[152.58,-26.50],"cap":"2 GW / 最高 48 GWh","inv":90,"invText":"约 90 亿美元（140 亿澳元）","status":"在建","year":2030,"updated":"2025-06","owner":"Queensland Hydro","flagship":true,"desc":"昆士兰旗舰抽蓄，2GW、储能容量达 48GWh。","detail":"位于昆士兰州因比尔(Imbil)附近博伦巴水库，装机 2GW、储能容量最高约 48GWh，可持续放电约 24 小时，是昆州能源转型的旗舰长时储能。2025 年获联邦环评批准开展前期工程，6 月由昆州投资公司(QIC)接管推进商业方案，正进行场地准备与营地建设。","progress":"2025-06 获环评批准并启动前期工程"},
  {"id":2627,"name":"沃伦电池储能（伍仁）","en":"Wooreen Battery Energy Storage System","country":"澳大利亚","region":"大洋洲","cat":"storage","coord":[146.50,-38.30],"cap":"350 MW / 1.4 GWh（4 小时）","inv":3.5,"invText":"约 3.5 亿美元","status":"在建","year":2026,"updated":"2025-06","owner":"EnergyAustralia","flagship":false,"desc":"维州拉特罗布河谷 350MW/1.4GWh 四小时电池。","detail":"位于维多利亚州拉特罗布河谷原燃煤电厂区，由 EnergyAustralia 开发，装机 350MW/1.4GWh、四小时时长，2025 年一季度达成融资承诺并开工，是维州河谷地区燃煤退役后转型的标志性大型电池储能。","progress":"2025 年融资承诺并开工建设"},
  {"id":2628,"name":"石灰岩海岸储能园（太平洋绿能）","en":"Limestone Coast Energy Park BESS","country":"澳大利亚","region":"大洋洲","cat":"storage","coord":[140.60,-37.40],"cap":"1 GW / 2.5 GWh","inv":7,"invText":"约 7 亿美元","status":"规划","year":2027,"updated":"2025-08","owner":"Pacific Green","flagship":true,"desc":"南澳 1GW/2.5GWh 大型电池储能园。","detail":"位于南澳州东南石灰岩海岸地区，由 Pacific Green 开发，规划装机 1GW/2.5GWh，是澳洲规划中规模最大的独立电池储能园之一。公司已收购项目用地并推进审批，服务南澳高比例可再生电网的稳定与跨州套利。","progress":"2025 年完成购地，推进审批与开发"},
  {"id":2629,"name":"烤炉山抽水蓄能","en":"Oven Mountain Pumped Hydro","country":"澳大利亚","region":"大洋洲","cat":"storage","coord":[152.00,-30.80],"cap":"约 900 MW / 12 小时","inv":13,"invText":"约 13 亿美元","status":"规划","year":2030,"updated":"2025-07","owner":"Oven Mountain Pumped Hydro / Alinta","flagship":false,"desc":"新州新英格兰 REZ 配套长时抽蓄。","detail":"位于新南威尔士州新英格兰可再生能源区，规划装机约 900MW、长时(约 12 小时)抽水蓄能，作为该 REZ 大规模风光的长时调节电源，2025 年推进可研与审批，强化新州长时储能能力。","progress":"2025 年推进可研与环评审批"},
  {"id":2630,"name":"莱尔湖抽水蓄能","en":"Lake Lyell Pumped Hydro","country":"澳大利亚","region":"大洋洲","cat":"storage","coord":[150.00,-33.50],"cap":"约 335 MW / 8 小时","inv":3.5,"invText":"约 3.5 亿美元","status":"规划","year":2029,"updated":"2025-06","owner":"EnergyAustralia","flagship":false,"desc":"新州利斯戈附近抽蓄，复用既有水库。","detail":"位于新南威尔士州利斯戈(Lithgow)附近莱尔湖，由 EnergyAustralia 开发，复用既有水库建设约 335MW、8 小时抽水蓄能，靠近退役燃煤与既有输电走廊，是新州近期推进的中型抽蓄项目。","progress":"2025 年推进审批与设计"},
  {"id":2631,"name":"史密斯菲尔德电池储能（伊维尔德罗拉）","en":"Smithfield Battery (Iberdrola)","country":"澳大利亚","region":"大洋洲","cat":"storage","coord":[150.93,-33.85],"cap":"65 MW / 130 MWh","inv":0.9,"invText":"约 0.9 亿美元","status":"投运","year":2026,"updated":"2026-02","owner":"Iberdrola Australia","flagship":false,"desc":"西悉尼 65MW/130MWh 城市电池，提前投运。","detail":"位于新南威尔士州西悉尼史密斯菲尔德，由西班牙 Iberdrola 开发，装机 65MW/130MWh，2026 年初提前建成投运，靠近城市负荷中心提供调频与电压支撑，是 Iberdrola 在新州能源转型布局的城市电池项目。","progress":"2026-02 提前建成并投入运营"},
  {"id":2632,"name":"亨特利调峰电池（新西兰）","en":"Huntly Firming Battery (NZ)","country":"新西兰","region":"大洋洲","cat":"storage","coord":[175.15,-37.55],"cap":"约 100 MW / 200 MWh","inv":1.5,"invText":"约 1.5 亿美元","status":"在建","year":2026,"updated":"2025-10","owner":"Genesis Energy","flagship":false,"desc":"新西兰北岛火电厂址调峰电池储能。","detail":"位于新西兰北岛亨特利(Huntly)发电厂区，由 Genesis Energy 投建约 100MW/200MWh 电池储能，复用既有并网点为北岛提供调峰与可再生消纳支撑，配合新西兰逐步减少煤气调峰的长期目标。","progress":"2025 年开工建设，目标 2026 投运"},
  {"id":2633,"name":"塔龙储能与燃煤转型电池（昆州）","en":"Tarong Battery (Stanwell)","country":"澳大利亚","region":"大洋洲","cat":"storage","coord":[151.91,-26.74],"cap":"约 300 MW / 600 MWh","inv":3,"invText":"约 3 亿美元","status":"在建","year":2026,"updated":"2025-09","owner":"Stanwell","flagship":false,"desc":"昆士兰国企塔龙电厂址大型电池。","detail":"由昆士兰州国企 Stanwell 在塔龙(Tarong)燃煤电厂区建设的约 300MW/600MWh 电池储能，复用既有变电与并网设施，是昆州'清洁能源公司'转型的组成部分，提供调峰与可再生消纳服务。","progress":"2025 年开工，配合燃煤逐步退出"},

  // ===== 工商业·配网大客户（绿色冶金/关键矿物加工）（2634-2641）=====
  {"id":2634,"name":"怀阿拉绿钢转型工程","en":"Whyalla Green Steel Transformation","country":"澳大利亚","region":"大洋洲","cat":"ci","coord":[137.56,-33.03],"cap":"电弧炉绿钢 + 绿铁","inv":16,"invText":"约 16 亿美元（24 亿澳元）","status":"在建","year":2027,"updated":"2025-06","owner":"GFG/政府接管 + 绿铁基金","flagship":true,"desc":"南澳怀阿拉钢厂电弧炉绿钢改造旗舰。","detail":"南澳州怀阿拉钢铁厂以电弧炉替代燃煤高炉、配低排放能源与废钢，转型生产绿钢与绿铁。州与联邦 2025 年宣布 24 亿澳元支持方案及 10 亿澳元绿铁投资基金(半数投向怀阿拉)，是澳洲绿色钢铁旗舰，目标 2027 年前后电弧炉投运。","progress":"2025 年政府接管并出台 24 亿澳元支持方案"},
  {"id":2635,"name":"托马戈铝冶炼厂绿色转型","en":"Tomago Aluminium Smelter Green Transition","country":"澳大利亚","region":"大洋洲","cat":"ci","coord":[151.70,-32.85],"cap":"澳洲最大铝厂约 59 万吨/年","inv":8,"invText":"约 8 亿美元","status":"规划","year":2028,"updated":"2025-12","owner":"力拓等 / 政府支持","flagship":true,"desc":"澳洲最大铝厂转用可再生电力。","detail":"位于新南威尔士州托马戈，是澳大利亚最大铝冶炼厂(约 59 万吨/年)，2028 年 AGL 供电合同到期前推进转用可再生电力。2025 年 12 月联邦承诺帮助锁定固定价购电协议与优惠融资，托马戈承诺十年内投入至少 10 亿澳元资本与维护，配合 20 亿澳元绿色铝生产抵免计划。","progress":"2025-12 获政府绿电与融资支持承诺"},
  {"id":2636,"name":"天齐奎纳纳氢氧化锂精炼厂","en":"Tianqi Kwinana Lithium Hydroxide Refinery","country":"澳大利亚","region":"大洋洲","cat":"ci","coord":[115.77,-32.24],"cap":"氢氧化锂约 4.8 万吨/年","inv":10,"invText":"约 10 亿美元","status":"投运","year":2025,"updated":"2025-08","owner":"天齐锂业 / IGO（Tianqi Lithium Energy Australia）","flagship":true,"desc":"南半球大型电池级氢氧化锂精炼厂。","detail":"位于西澳奎纳纳(Kwinana)工业区，由天齐锂业与 IGO 合资(TLEA)运营，以格林布什锂精矿为原料生产电池级氢氧化锂，一期约 2.4 万吨/年达产并推进二期，合计约 4.8 万吨/年，是南半球规模领先的锂盐精炼，服务全球动力电池供应链。","progress":"2025 年一期稳产并推进二期产能"},
  {"id":2637,"name":"雅保科默顿氢氧化锂工厂","en":"Albemarle Kemerton Lithium Hydroxide","country":"澳大利亚","region":"大洋洲","cat":"ci","coord":[115.78,-33.18],"cap":"氢氧化锂约 5 万吨/年","inv":8,"invText":"约 8 亿美元","status":"投运","year":2025,"updated":"2025-07","owner":"Albemarle","flagship":false,"desc":"西澳科默顿电池级锂盐加工基地。","detail":"位于西澳科默顿(Kemerton)工业区，由美国雅保(Albemarle)投建，以格林布什锂精矿为原料生产电池级氢氧化锂，建成产能约 5 万吨/年(两条产线)。受锂价波动影响阶段性优化运营，是西澳关键矿物下游加工的代表项目。","progress":"2025 年优化运营、两线产能爬坡"},
  {"id":2638,"name":"科瓦伦特霍兰山锂精炼厂（奎纳纳）","en":"Covalent Mt Holland Lithium Refinery","country":"澳大利亚","region":"大洋洲","cat":"ci","coord":[115.77,-32.23],"cap":"氢氧化锂约 5 万吨/年","inv":4,"invText":"约 4 亿美元","status":"在建","year":2026,"updated":"2025-09","owner":"Covalent Lithium（Wesfarmers / SQM）","flagship":false,"desc":"西澳奎纳纳新建锂盐精炼厂。","detail":"由 Wesfarmers 与智利 SQM 合资的 Covalent 在西澳奎纳纳建设的氢氧化锂精炼厂，配套霍兰山(Mt Holland / Earl Grey)锂矿精矿，规划约 5 万吨/年电池级氢氧化锂，2025-2026 年推进调试投产，强化西澳锂全产业链布局。","progress":"2025 年推进精炼厂建设与调试"},
  {"id":2639,"name":"阿尔法高纯氧化铝厂（格拉德斯通）","en":"Alpha HPA High Purity Alumina","country":"澳大利亚","region":"大洋洲","cat":"ci","coord":[151.20,-23.86],"cap":"高纯氧化铝约 1 万吨/年","inv":3.5,"invText":"约 3.5 亿美元","status":"在建","year":2026,"updated":"2025-08","owner":"Alpha HPA","flagship":false,"desc":"昆士兰格拉德斯通高纯氧化铝(电池/半导体级)。","detail":"位于昆士兰州格拉德斯通,由 Alpha HPA 建设的高纯氧化铝(HPA)精炼厂,采用无传统铝土矿工艺,一期约 1 万吨/年,产品用于锂电池隔膜涂层、LED 与半导体。获联邦关键矿物贷款支持,2025-2026 年推进一期投产。","progress":"2025 年一期建设推进，目标 2026 投产"},
  {"id":2640,"name":"雷纳斯科尔西维奥石墨负极一体化","en":"Renascor Siviour Graphite & Anode","country":"澳大利亚","region":"大洋洲","cat":"ci","coord":[136.50,-33.60],"cap":"球化石墨负极约 10 万吨/年","inv":2.5,"invText":"约 2.5 亿美元","status":"规划","year":2027,"updated":"2025-07","owner":"Renascor Resources","flagship":false,"desc":"南澳石墨矿+电池负极一体化。","detail":"位于南澳州埃尔半岛西维奥(Siviour)的天然石墨矿与电池负极(球化提纯石墨)一体化项目，规划负极年产约 10 万吨，获联邦关键矿物融资支持，旨在打造非中国的电池负极供应链，2025 年推进矿山与下游加工建设。","progress":"2025 年推进矿山与负极一体化开发"},
  {"id":2641,"name":"伊卢卡埃尼亚巴稀土精炼厂","en":"Iluka Eneabba Rare Earths Refinery","country":"澳大利亚","region":"大洋洲","cat":"ci","coord":[115.27,-29.82],"cap":"分离稀土氧化物（含 NdPr/Dy/Tb）","inv":12,"invText":"约 12 亿美元（18 亿澳元）","status":"在建","year":2027,"updated":"2025-10","owner":"Iluka Resources / 政府","flagship":true,"desc":"澳洲首座全产业链稀土精炼厂。","detail":"位于西澳埃尼亚巴(Eneabba)，由 Iluka Resources 建设，是澳大利亚首座全产业链稀土分离精炼厂，可生产钕镨(NdPr)及镝铽等重稀土氧化物。获联邦超 12 亿澳元贷款支持，原料来自 Eneabba 独居石库存与第三方精矿，建成后成为西方重要的非中国稀土分离产能，计划 2027 年投产。","progress":"2025 年主体建设推进，目标 2027 投产"},

  // ===== 数据中心（2642-2648）=====
  {"id":2642,"name":"微软澳大利亚 Azure AI 超算扩建","en":"Microsoft Azure AI Australia Expansion","country":"澳大利亚","region":"大洋洲","cat":"datacenter","coord":[150.85,-33.81],"cap":"Azure AI 算力，数据中心扩容约 140%","inv":120,"invText":"约 120 亿美元（250 亿澳元）","status":"在建","year":2027,"updated":"2026-04","owner":"Microsoft","flagship":true,"desc":"微软 250 亿澳元扩建澳洲云与 AI 超算。","detail":"微软 2026 年 4 月宣布投入约 250 亿澳元在澳大利亚新建 Azure AI 超算算力，并将既有数据中心规模扩大约 140%，集中布局于西悉尼等地。投资规模约为 AWS 132 亿澳元承诺的 1.9 倍，瞄准主权云与 GPU 密集的人工智能工作负载。","progress":"2026-04 公布 250 亿澳元 AI 扩建计划"},
  {"id":2643,"name":"亚马逊 AWS 澳大利亚云区扩建","en":"AWS Australia Cloud Investment","country":"澳大利亚","region":"大洋洲","cat":"datacenter","coord":[150.90,-33.80],"cap":"悉尼/墨尔本云区，2023-2027 扩建","inv":85,"invText":"约 85 亿美元（132 亿澳元）","status":"在建","year":2027,"updated":"2025-06","owner":"Amazon Web Services","flagship":true,"desc":"AWS 承诺 132 亿澳元扩建澳洲数据中心。","detail":"亚马逊云科技承诺在 2023-2027 年间投入约 132 亿澳元扩建澳大利亚悉尼与墨尔本云区数据中心基础设施，配套大规模可再生购电协议，支撑澳洲企业与政府云及生成式 AI 需求，是澳洲规模最大的云基础设施投资之一。","progress":"2025 年多站点持续建设扩容"},
  {"id":2644,"name":"谷歌云澳大利亚数据中心","en":"Google Cloud Australia Data Centres","country":"澳大利亚","region":"大洋洲","cat":"datacenter","coord":[151.10,-33.85],"cap":"悉尼/墨尔本云区与 AI 基础设施","inv":30,"invText":"约 30 亿美元","status":"在建","year":2027,"updated":"2025-09","owner":"Google","flagship":false,"desc":"谷歌持续扩建澳洲云与 AI 算力。","detail":"谷歌在悉尼与墨尔本持续扩建云区数据中心及 AI 算力基础设施，配套数字未来计划与可再生能源采购，服务澳新地区企业云、搜索与生成式 AI 负载，是澳洲超大规模云基础设施的主要参与者之一。","progress":"2025 年持续推进数据中心与算力扩容"},
  {"id":2645,"name":"NextDC 悉尼 S6 超大规模数据中心","en":"NextDC S6 Sydney Hyperscale","country":"澳大利亚","region":"大洋洲","cat":"datacenter","coord":[150.95,-33.80],"cap":"规划 IT 容量逾 300MW","inv":7,"invText":"约 7 亿美元","status":"在建","year":2027,"updated":"2025-10","owner":"NextDC","flagship":false,"desc":"澳洲本土超大规模数据中心新站。","detail":"由澳洲本土数据中心龙头 NextDC 在大悉尼地区开发的新一代超大规模数据中心，规划 IT 容量逾 300MW，面向云厂商与 AI 客户的高密度 GPU 机柜需求，2025-2026 年分阶段建设交付。","progress":"2025 年开工建设，分阶段交付"},
  {"id":2646,"name":"CDC 悉尼主权云数据中心园","en":"CDC Data Centres Sydney Campus","country":"澳大利亚","region":"大洋洲","cat":"datacenter","coord":[151.00,-33.86],"cap":"多座园区，逾 500MW","inv":13,"invText":"约 13 亿美元","status":"在建","year":2027,"updated":"2025-08","owner":"CDC Data Centres","flagship":true,"desc":"澳洲主权云龙头，悉尼/堪培拉大型园区。","detail":"CDC Data Centres 是澳大利亚政府与主权云的主要承载方，在悉尼与堪培拉建设多座大型数据中心园区，总规划容量逾 500MW，满足政府、国防与超大规模云客户的高可用与本地化需求，2025-2026 年持续扩建。","progress":"2025 年多园区扩建推进"},
  {"id":2647,"name":"AirTrunk 悉尼 SYD 超大规模园区","en":"AirTrunk SYD Hyperscale Campus","country":"澳大利亚","region":"大洋洲","cat":"datacenter","coord":[150.92,-33.79],"cap":"逾 400MW","inv":13,"invText":"约 13 亿美元","status":"在建","year":2027,"updated":"2025-09","owner":"AirTrunk（黑石等）","flagship":false,"desc":"亚太超大规模数据中心，西悉尼扩容。","detail":"AirTrunk(被黑石等收购)在西悉尼亨廷伍德等地的超大规模数据中心园区，规划容量逾 400MW，服务全球云与 AI 客户，配套大规模可再生购电，是亚太地区领先的 hyperscale 平台之一，持续扩容。","progress":"2025 年园区持续扩建"},
  {"id":2648,"name":"STACK 基础设施悉尼数据中心","en":"STACK Infrastructure Sydney Data Centre","country":"澳大利亚","region":"大洋洲","cat":"datacenter","coord":[150.90,-33.81],"cap":"逾 200MW","inv":7,"invText":"约 7 亿美元","status":"规划","year":2028,"updated":"2025-11","owner":"STACK Infrastructure","flagship":false,"desc":"西悉尼新建超大规模数据中心。","detail":"美资 STACK Infrastructure 在西悉尼开发的超大规模数据中心，规划 IT 容量逾 200MW，面向云与 AI 客户的高密度需求，2025 年推进用地与审批，是澳洲数据中心新进入者的代表项目。","progress":"2025 年推进选址与审批"},

  // ===== 大交通（轨交·机场·港口）（2649-2656）=====
  {"id":2649,"name":"悉尼地铁—西悉尼机场线","en":"Sydney Metro – Western Sydney Airport","country":"澳大利亚","region":"大洋洲","cat":"transport","coord":[150.75,-33.88],"cap":"约 23 公里自动化地铁","inv":72,"invText":"约 72 亿美元（110 亿澳元）","status":"在建","year":2026,"updated":"2025-12","owner":"Sydney Metro","flagship":true,"desc":"连接西悉尼新机场的自动化地铁，2026 通车。","route":[[150.69,-33.88],[150.84,-33.86]],"detail":"约 23 公里自动化地铁，连接圣玛丽斯与西悉尼国际机场及奥兰多新城，总投资约 110 亿澳元，设多座新站。预计 2026 年底与西悉尼新机场同步开通，是新州最大轨交工程之一，将带动西悉尼'航空城'发展。","progress":"2025-12 进入系统调试，2026 底拟通车"},
  {"id":2650,"name":"悉尼地铁西段（帕拉马塔—CBD）","en":"Sydney Metro West","country":"澳大利亚","region":"大洋洲","cat":"transport","coord":[151.00,-33.83],"cap":"约 24 公里地下地铁","inv":110,"invText":"约 110 亿美元","status":"在建","year":2030,"updated":"2025-10","owner":"Sydney Metro","flagship":true,"desc":"帕拉马塔至悉尼 CBD 全地下地铁。","route":[[151.00,-33.81],[151.21,-33.87]],"detail":"全长约 24 公里的全地下自动化地铁，连接帕拉马塔与悉尼 CBD，大幅提升两大商务中心间运能。隧道掘进已推进，是新州投资规模最大的轨交工程之一，计划 2030 年前后通车。","progress":"2025 年隧道与车站施工推进"},
  {"id":2651,"name":"墨尔本机场轨道连接线","en":"Melbourne Airport Rail","country":"澳大利亚","region":"大洋洲","cat":"transport","coord":[144.84,-37.67],"cap":"机场至 CBD 重轨连接","inv":85,"invText":"约 85 亿美元（130 亿澳元）","status":"在建","year":2030,"updated":"2025-09","owner":"维州大建设 / 联邦","flagship":true,"desc":"墨尔本机场至市区重轨，联邦投资约 70 亿澳元。","route":[[144.84,-37.67],[144.96,-37.81]],"detail":"连接墨尔本机场与市中心的重轨工程，联邦政府出资约 70 亿澳元(总投资约 130 亿澳元)。一期西富茨克雷至阿尔比恩铁路升级已开工，2030 年完工，轨道改线 2026 年起在机场站周边推进，是维州重大交通项目。","progress":"2025 年一期升级开工，2026 推进站区改线"},
  {"id":2652,"name":"内陆铁路（墨尔本—布里斯班）","en":"Inland Rail (Melbourne–Brisbane)","country":"澳大利亚","region":"大洋洲","cat":"transport","coord":[148.00,-31.50],"cap":"约 1700 公里货运铁路","inv":200,"invText":"约 200 亿美元（310 亿澳元）","status":"在建","year":2027,"updated":"2025-08","owner":"Australian Rail Track Corporation (ARTC)","flagship":true,"desc":"贯通东海岸的 1700 公里货运铁路大动脉。","route":[[144.96,-37.81],[153.03,-27.47]],"detail":"全长逾 1700 公里、连接墨尔本与布里斯班的货运铁路网络，总投资约 310 亿澳元，分多段建设。通过内陆走廊缩短东海岸货运时间、提升供应链效率，部分段已通车，墨尔本—帕克斯段持续推进，是澳洲规模最大的铁路工程。","progress":"2025 年多标段施工，南段陆续贯通"},
  {"id":2653,"name":"墨尔本郊区环线（东段 SRL East）","en":"Suburban Rail Loop East","country":"澳大利亚","region":"大洋洲","cat":"transport","coord":[145.10,-37.88],"cap":"约 26 公里地下环线（东段）","inv":220,"invText":"约 220 亿美元（340 亿澳元）","status":"在建","year":2035,"updated":"2025-10","owner":"Suburban Rail Loop Authority","flagship":true,"desc":"墨尔本东郊地下环线，连接多条放射线。","route":[[145.07,-37.92],[145.13,-37.78]],"detail":"墨尔本郊区环线东段(SRL East)约 26 公里全地下铁路，连接彻尔滕纳姆至博士山，串联东南郊多条放射式铁路与大学、医疗中心。总投资约 340 亿澳元，隧道掘进 2025 年起推进，是维州历史上规模最大的公共交通工程。","progress":"2025 年隧道掘进机进场，主体开工"},
  {"id":2654,"name":"墨尔本东北连接线（North East Link）","en":"North East Link","country":"澳大利亚","region":"大洋洲","cat":"transport","coord":[145.10,-37.75],"cap":"约 6.5 公里双层隧道高速","inv":170,"invText":"约 170 亿美元（260 亿澳元）","status":"在建","year":2028,"updated":"2025-09","owner":"维州大建设","flagship":true,"desc":"维州最大道路工程，含双层隧道。","detail":"墨尔本东北连接线含约 6.5 公里双层隧道，连接东部高速与 M80 环路，是维多利亚州历史上规模最大的道路工程，总投资约 260 亿澳元。隧道掘进 2025 年推进，建成后大幅缓解东北郊拥堵，计划 2028 年通车。","progress":"2025 年隧道掘进推进，2028 拟通车"},
  {"id":2655,"name":"西港隧道（悉尼）","en":"Western Harbour Tunnel (Sydney)","country":"澳大利亚","region":"大洋洲","cat":"transport","coord":[151.18,-33.85],"cap":"约 6.5 公里港湾隧道","inv":85,"invText":"约 85 亿美元（130 亿澳元）","status":"在建","year":2028,"updated":"2025-08","owner":"Transport for NSW","flagship":false,"desc":"悉尼港第二条机动车越港隧道。","detail":"约 6.5 公里的悉尼港越港隧道，为现有海港大桥与隧道分流，连接西部 distributor 与北悉尼，总投资约 130 亿澳元。沉管与盾构施工推进，计划 2028 年通车，是大悉尼路网的关键工程。","progress":"2025 年隧道施工推进"},
  {"id":2656,"name":"布里斯班 2032 奥运交通枢纽工程","en":"Brisbane 2032 Transport Infrastructure","country":"澳大利亚","region":"大洋洲","cat":"transport","coord":[153.02,-27.47],"cap":"轨交/快速公交/场馆配套","inv":60,"invText":"约 60 亿美元","status":"规划","year":2031,"updated":"2025-11","owner":"昆士兰州政府","flagship":false,"desc":"配套布里斯班 2032 奥运的交通基础设施。","detail":"为布里斯班 2032 年奥运会配套的交通基础设施集群，含轨道、快速公交(Brisbane Metro 扩展)、场馆连接与机场升级等，提升东南昆士兰公共交通运能与城市互联，2025 年起陆续推进规划与建设。","progress":"2025 年推进规划与前期工程"},

  // ===== 石油化工·油气·LNG（2657-2666）=====
  {"id":2657,"name":"巴罗萨气田（达尔文 LNG 回填）","en":"Barossa Gas Project","country":"澳大利亚","region":"大洋洲","cat":"petro","coord":[130.80,-9.70],"cap":"LNG 约 370 万吨/年","inv":38,"invText":"约 38 亿美元（58 亿澳元）","status":"投运","year":2025,"updated":"2026-06","owner":"Santos / SK E&S / JERA","flagship":true,"desc":"为达尔文 LNG 回填的海上气田，2025 年首气。","detail":"位于北领地达尔文以北约 300 公里海域，由 Santos 牵头开发，FPSO 加海底管线为达尔文 LNG 工厂回填，满产 LNG 约 370 万吨/年。2025 年 10 月实现首次投产气，标志从建设转入投产阶段，是澳洲北部重要天然气供应来源。","progress":"BW Opal FPSO 于2025年9月实现首气，2026年1月25日达尔文LNG装出首船巴罗萨LNG驶往日本堺港，项目正式投产。"},
  {"id":2658,"name":"克拉克斯气田（Prelude 回填）","en":"Crux Gas Project","country":"澳大利亚","region":"大洋洲","cat":"petro","coord":[123.90,-13.90],"cap":"为 Prelude FLNG 回填","inv":25,"invText":"约 25 亿美元","status":"在建","year":2027,"updated":"2025-07","owner":"Shell / SGH Energy","flagship":false,"desc":"布劳斯盆地气田，为 Prelude 浮式 LNG 供气。","detail":"位于西澳布劳斯盆地北部，由壳牌牵头开发，2024 年批准新钻井与设施安装，为 Prelude 浮式 LNG(FLNG)提供关键回填气源，延长其满产寿命，计划 2027 年前后供气。","progress":"2025 年钻井与平台安装推进"},
  {"id":2659,"name":"布劳斯 LNG 开发","en":"Browse LNG Development","country":"澳大利亚","region":"大洋洲","cat":"petro","coord":[123.30,-14.00],"cap":"为西北大陆架供气","inv":200,"invText":"约 200 亿美元","status":"规划","year":2031,"updated":"2025-09","owner":"Woodside / 合资方","flagship":true,"desc":"澳洲最大未开发气田，西北大陆架回填。","detail":"位于西澳布劳斯盆地，是澳大利亚最大的未开发常规天然气资源之一，规划经海底管线为既有西北大陆架(NWS)卡拉萨工厂回填，延续其 LNG 出口。项目需通过环保审批，2025 年推进环评与商业安排，目标 2030 年代投产。","progress":"2025 年推进环评与最终投资准备"},
  {"id":2660,"name":"皮尼扬 LNG 项目（巴新）","en":"P'nyang LNG (PNG)","country":"巴布亚新几内亚","region":"大洋洲","cat":"petro","coord":[141.50,-5.50],"cap":"扩建 LNG 列车","inv":50,"invText":"约 50 亿美元","status":"规划","year":2030,"updated":"2025-12","owner":"ExxonMobil / Santos / JX","flagship":false,"desc":"巴新继 Papua LNG 之后的下一个 LNG 扩建。","detail":"位于巴布亚新几内亚西部省皮尼扬(P'nyang)气田，由埃克森美孚牵头，原拟与 Papua LNG 并行，后按巴新政府安排排在其后推进，为 PNG LNG 工厂新增液化列车，2025 年推进商业谈判与开发方案。","progress":"2025 年推进开发方案与政府协议"},
  {"id":2661,"name":"比特鲁页岩气开发（北领地）","en":"Beetaloo Basin Shale Gas","country":"澳大利亚","region":"大洋洲","cat":"petro","coord":[134.50,-16.50],"cap":"页岩气大规模开发","inv":15,"invText":"约 15 亿美元","status":"在建","year":2026,"updated":"2025-10","owner":"Tamboran Resources / Empire Energy","flagship":true,"desc":"澳洲最具潜力页岩气盆地，北领地开发。","detail":"位于北领地比特鲁(Beetaloo)盆地，是澳大利亚最具潜力的页岩气资源区。Tamboran 与 Empire Energy 推进先导开发与商业产气，规划管输至达尔文及东海岸气网，并研究 LNG 出口，2025-2026 年进入早期商业生产阶段。","progress":"2025 年先导井投产，推进商业开发"},
  {"id":2662,"name":"库里库里调峰燃气电站（猎人电力）","en":"Kurri Kurri Gas Plant (Hunter Power)","country":"澳大利亚","region":"大洋洲","cat":"petro","coord":[151.48,-32.82],"cap":"660 MW 开式燃气","inv":7,"invText":"约 7 亿美元（约 10 亿澳元）","status":"投运","year":2025,"updated":"2025-12","owner":"Snowy Hydro","flagship":false,"desc":"新州猎人谷 660MW 调峰燃气电厂。","detail":"位于新南威尔士州猎人谷库里库里，由 Snowy Hydro 投建的 660MW 开式循环燃气调峰电厂，最终造价约 10 亿澳元，可掺烧绿氢。2025 年底投运，为可再生波动提供灵活支撑，配合利德尔燃煤退役后的供电充裕。","progress":"2025 年底建成投运"},
  {"id":2663,"name":"塔拉瓦拉 B 双燃料调峰电站","en":"Tallawarra B Dual-Fuel Power Station","country":"澳大利亚","region":"大洋洲","cat":"petro","coord":[150.83,-34.55],"cap":"316 MW 燃气/氢双燃料","inv":3,"invText":"约 3 亿美元","status":"投运","year":2024,"updated":"2025-06","owner":"EnergyAustralia","flagship":false,"desc":"澳洲首座氢气混烧调峰燃气电厂。","detail":"位于新南威尔士州伊拉瓦拉湖西岸，由 EnergyAustralia 投建的 316MW 调峰燃气电厂，可掺烧约 5% 体积的可再生氢，是澳大利亚首座具备氢气混烧能力的燃气电站，2024 年建成、为电网提供灵活调峰支撑。","progress":"2024 年投运，2025 年掺氢运行"},
  {"id":2664,"name":"纳拉布里天然气项目","en":"Narrabri Gas Project","country":"澳大利亚","region":"大洋洲","cat":"petro","coord":[149.90,-30.40],"cap":"煤层气，约 200TJ/日","inv":24,"invText":"约 24 亿美元（36 亿澳元）","status":"规划","year":2028,"updated":"2025-08","owner":"Santos","flagship":false,"desc":"新州内陆煤层气，缓解东海岸气荒。","detail":"位于新南威尔士州纳拉布里附近，由 Santos 开发的煤层气项目，规划产能约 200TJ/日，可满足新州约一半天然气需求，缓解东海岸供气紧张。项目历经长期审批与社区争议，2025 年推进开发审批与管道安排。","progress":"2025 年推进审批与管道前期"},
  {"id":2665,"name":"西北大陆架延寿工程（卡拉萨）","en":"North West Shelf Extension (Karratha)","country":"澳大利亚","region":"大洋洲","cat":"petro","coord":[116.76,-20.60],"cap":"延续 LNG 出口至 2070","inv":12,"invText":"约 12 亿美元","status":"规划","year":2027,"updated":"2025-06","owner":"Woodside / 合资方","flagship":false,"desc":"澳洲最老 LNG 工厂延寿至 2070 年。","detail":"位于西澳卡拉萨的西北大陆架(NWS)是澳大利亚最早的 LNG 出口基地，Woodside 推进将运营许可延长至 2070 年的环境审批，配合布劳斯等新气源回填，2025 年获联邦初步批准，延续其长期 LNG 出口能力。","progress":"2025 年获联邦延寿初步批准"},
  {"id":2666,"name":"肯布拉港 LNG 进口接收站","en":"Port Kembla Energy Terminal","country":"澳大利亚","region":"大洋洲","cat":"petro","coord":[150.90,-34.47],"cap":"FSRU 进口接收","inv":3,"invText":"约 3 亿美元","status":"投运","year":2025,"updated":"2025-07","owner":"Squadron Energy","flagship":false,"desc":"澳洲东海岸首座 LNG 进口接收站。","detail":"位于新南威尔士州肯布拉港，由 Squadron Energy(福雷斯特旗下)建设的浮式储存再气化(FSRU)LNG 进口接收站，是澳洲东海岸首座 LNG 进口终端，用于缓解东南部冬季天然气短缺，2025 年具备接收能力。","progress":"2025 年终端具备进口接收能力"},

  // ===== 矿业（2667-2680）=====
  {"id":2667,"name":"奥林匹克坝铜金铀扩建（必和必拓）","en":"Olympic Dam Copper-Gold-Uranium Expansion","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[136.88,-30.44],"cap":"铜增至 65 万吨/年（远期）","inv":12,"invText":"约 12 亿美元","status":"在建","year":2028,"updated":"2025-12","owner":"BHP","flagship":true,"desc":"全球级铜金铀矿，冲刺 65 万吨/年铜。","detail":"位于南澳州，是全球最重要的铜-金-铀-镍综合矿床之一。必和必拓投入逾 8.4 亿美元推进南部矿区斜井、充填系统、扩能溜井与新氧气厂等成长项目，并评估冶炼精炼扩建以将铜产能提至 65 万吨/年，重大扩建决定预计 2028 年作出。","progress":"2025-12 推进 8.4 亿美元成长工程"},
  {"id":2668,"name":"霍普唐斯 2 号铁矿（力拓/汉考克）","en":"Hope Downs 2 Iron Ore","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[119.50,-23.00],"cap":"3100 万吨/年","inv":16,"invText":"约 16 亿美元","status":"在建","year":2027,"updated":"2025-08","owner":"Rio Tinto / Hancock Prospecting","flagship":false,"desc":"皮尔巴拉新建铁矿，年产 3100 万吨。","detail":"位于西澳皮尔巴拉，力拓与汉考克(Hancock)合资投资约 16.1 亿美元开发，含两座地下水位上铁矿坑，合计年产能 3100 万吨，配套基础设施，首矿预计 2027 年，延续皮尔巴拉铁矿产能。","progress":"2025 年开发推进，首矿目标 2027"},
  {"id":2669,"name":"布罗克曼向斜 1 号铁矿","en":"Brockman Syncline 1 (BS1)","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[117.30,-22.60],"cap":"延续布罗克曼产区产能","inv":18,"invText":"约 18 亿美元","status":"在建","year":2027,"updated":"2025-07","owner":"Rio Tinto","flagship":false,"desc":"力拓 18 亿美元延寿西皮尔巴拉布罗克曼。","detail":"位于西澳西皮尔巴拉，力拓投资约 18 亿美元开发布罗克曼向斜 1 号(BS1)矿，延长布罗克曼产区寿命，首矿现定于 2027 年，是力拓维持皮尔巴拉铁矿产能的关键替代项目。","progress":"2025 年建设推进，首矿目标 2027"},
  {"id":2670,"name":"西部山脉铁矿（力拓/宝武）","en":"Western Range Iron Ore","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[117.70,-23.20],"cap":"2500 万吨/年","inv":20,"invText":"约 20 亿美元","status":"投运","year":2025,"updated":"2025-09","owner":"Rio Tinto (54%) / 中国宝武 (46%)","flagship":true,"desc":"力拓与宝武合资铁矿，按期按预算建成。","detail":"位于西澳帕拉伯杜附近，由力拓(54%)与中国宝武(46%)合资开发，年产能 2500 万吨，总投资约 20 亿美元，按期按预算建成投产，是中澳铁矿合作的标志性项目，巩固皮尔巴拉对华铁矿供应。","progress":"2025 年建成投产并爬坡"},
  {"id":2671,"name":"西安吉拉斯维持性铁矿项目","en":"West Angelas Sustaining Project","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[118.70,-23.10],"cap":"维持西安吉拉斯产能","inv":7.3,"invText":"约 7.3 亿美元","status":"在建","year":2027,"updated":"2025-06","owner":"Rio Tinto / Mitsui / Nippon Steel","flagship":false,"desc":"力拓与日企合资维持皮尔巴拉铁矿产能。","detail":"位于西澳皮尔巴拉，力拓与三井物产、日本制铁合资投资约 7.33 亿美元开发新矿坑，维持西安吉拉斯铁矿产能，首矿预计 2027 年，是皮尔巴拉铁矿产能接续的组成部分。","progress":"2025 年开发推进，首矿目标 2027"},
  {"id":2672,"name":"罗兹岭铁矿（一期）","en":"Rhodes Ridge Iron Ore","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[119.30,-23.00],"cap":"世界级未开发铁矿","inv":25,"invText":"约 25 亿美元","status":"规划","year":2030,"updated":"2025-08","owner":"Rio Tinto JV / Wright Prospecting","flagship":true,"desc":"皮尔巴拉最大未开发铁矿之一。","detail":"位于西澳皮尔巴拉，是世界上规模最大、品位最高的未开发铁矿之一。罗兹岭合资体 2025 年批准约 1.91 亿美元可研推进一期开发，规划产能巨大，目标 2030 年代初首矿，是力拓中长期铁矿产能的核心增长极。","progress":"2025 年批准一期可研研究"},
  {"id":2673,"name":"铁桥磁铁矿（FMG）","en":"Iron Bridge Magnetite","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[118.60,-21.50],"cap":"高品位磁精矿 2200 万吨/年","inv":39,"invText":"约 39 亿美元","status":"投运","year":2025,"updated":"2025-06","owner":"Fortescue / Formosa","flagship":true,"desc":"FMG 高品位磁铁矿，年产 2200 万吨精矿。","detail":"位于西澳皮尔巴拉，由福特斯库(FMG)与台塑合资开发的磁铁矿项目，年产高品位(67%)磁精矿约 2200 万吨，总投资约 39 亿美元，2023 年首批精矿、2025 年产能持续爬坡，提供更适合绿色炼钢的高品位原料。","progress":"2025 年产能持续爬坡上量"},
  {"id":2674,"name":"安多弗锂矿（汉考克/SQM）","en":"Andover Lithium Mine","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[117.10,-20.80],"cap":"硬岩锂矿","inv":10,"invText":"约 10 亿美元","status":"规划","year":2028,"updated":"2025-09","owner":"Hancock Prospecting / SQM","flagship":false,"desc":"皮尔巴拉新建锂矿，汉考克与 SQM 合资。","detail":"位于西澳皮尔巴拉罗伯恩附近，由汉考克与智利锂业巨头 SQM 合资开发，计划 2028 年起建设约 10 亿美元级硬岩锂矿，是皮尔巴拉锂资源带的新成员，强化澳洲对全球锂供应链的话语权。","progress":"2025 年推进可研，拟 2028 开工"},
  {"id":2675,"name":"布朗斯山脉重稀土项目","en":"Browns Range Heavy Rare Earths","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[128.20,-19.00],"cap":"镝铽等重稀土","inv":2.5,"invText":"约 2.5 亿美元","status":"规划","year":2027,"updated":"2025-07","owner":"Northern Minerals","flagship":false,"desc":"澳洲少有的重稀土(镝铽)资源项目。","detail":"位于西澳与北领地交界的布朗斯山脉，由 Northern Minerals 开发，富含镝、铽等重稀土，是中国以外少有的重稀土供应来源，对国防与高端电机磁材意义重大，2025 年推进开发与下游分离合作。","progress":"2025 年推进开发与融资"},
  {"id":2676,"name":"达博稀土多金属项目（ASM）","en":"Dubbo Rare Earths Project","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[148.70,-32.40],"cap":"稀土+锆铪铌","inv":12,"invText":"约 12 亿美元（18 亿澳元）","status":"规划","year":2029,"updated":"2025-08","owner":"Australian Strategic Materials (ASM)","flagship":false,"desc":"新州稀土与战略金属一体化项目。","detail":"位于新南威尔士州达博附近，由 ASM 开发，含稀土及锆、铪、铌等战略金属，规划矿山与精炼一体化，对接 ASM 韩国金属厂，打造非中国稀土-金属-磁材供应链，2025 年推进融资与最终投资决定。","progress":"2025 年推进融资与 FID"},
  {"id":2677,"name":"博丁顿金铜矿扩产（纽蒙特）","en":"Boddington Gold Mine Expansion","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[116.40,-32.80],"cap":"澳洲最大金矿之一","inv":4,"invText":"约 4 亿美元","status":"在建","year":2026,"updated":"2025-06","owner":"Newmont","flagship":false,"desc":"西澳最大金矿，自动化卡车扩产。","detail":"位于西澳博丁顿，是澳大利亚最大的金(铜)矿之一，纽蒙特推进自动化运输车队与采区拓展以延长矿山寿命、稳定金铜产量，2025-2026 年持续投入，是西澳黄金生产的支柱矿山。","progress":"2025 年自动化与扩产投入推进"},
  {"id":2678,"name":"卡迪亚金铜矿延伸（纽蒙特）","en":"Cadia Gold-Copper Extension","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[148.99,-33.45],"cap":"长寿命金铜地下矿","inv":14,"invText":"约 14 亿美元","status":"在建","year":2027,"updated":"2025-07","owner":"Newmont","flagship":false,"desc":"新州长寿命金铜矿，崩落法扩区。","detail":"位于新南威尔士州奥兰治附近，是澳大利亚最大的地下金铜矿之一。纽蒙特推进新一期崩落法采区(如 PC1-2/PC2-3)与尾矿扩容，延长矿山寿命至 2040 年代，2025-2026 年持续资本投入。","progress":"2025 年崩落法新区与尾矿扩容推进"},
  {"id":2679,"name":"哈维隆金铜矿（纽蒙特/格雷特兰）","en":"Havieron Gold-Copper Project","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[123.00,-21.00],"cap":"高品位金铜地下矿","inv":5,"invText":"约 5 亿美元","status":"在建","year":2027,"updated":"2025-09","owner":"Greatland Resources / Newmont","flagship":false,"desc":"西澳帕特森省高品位金铜新矿。","detail":"位于西澳帕特森省，由 Greatland 与纽蒙特合作开发的高品位金铜地下矿，矿石拟运往邻近 Telfer 工厂处理，2025 年推进竖井与开发巷道建设，是西澳金铜的重要新增产能。","progress":"2025 年竖井与开拓工程推进"},
  {"id":2680,"name":"哈尼木铀矿复产（博斯能源）","en":"Honeymoon Uranium Restart","country":"澳大利亚","region":"大洋洲","cat":"mining","coord":[140.60,-31.90],"cap":"原地浸出铀矿","inv":2,"invText":"约 2 亿美元","status":"投运","year":2025,"updated":"2025-06","owner":"Boss Energy","flagship":false,"desc":"南澳原地浸出铀矿复产，供应全球核电。","detail":"位于南澳州东北的原地浸出(ISR)铀矿，由 Boss Energy 投资复产，2024 年起恢复生产铀精矿并扩产，受益于全球核电复兴与铀价上行，是澳大利亚少数在产铀矿之一，主要面向出口。","progress":"2025 年复产并推进扩产爬坡"},

  // ===== 国际大客户（中国出海龙头在澳项目）（2681-2682）=====
  {"id":2681,"name":"比亚迪澳大利亚矿用与电网电池供应","en":"BYD Australia Mining & Grid Battery Supply","country":"澳大利亚","region":"大洋洲","cat":"client","coord":[119.70,-22.42],"cap":"矿区储能 + 网级电池供货","inv":2.5,"invText":"约 2.5 亿美元","status":"在建","year":2026,"updated":"2025-11","owner":"比亚迪","flagship":false,"desc":"比亚迪为福特斯库等供应大规模储能电池。","detail":"比亚迪(BYD)为澳大利亚矿业与电网储能市场供应大规模磷酸铁锂电池系统，包括为福特斯库皮尔巴拉离网清洁能源网络供货(如克劳德布雷克 74MW/650MWh 矿区储能)，并参与多个网级 BESS。2025 年澳洲成为中国电池企业重要海外市场，比亚迪份额持续扩大。","progress":"2025 年矿区与网级电池订单交付推进"},
  {"id":2682,"name":"宁德时代澳大利亚网级储能供应","en":"CATL Australia Grid-Scale Storage Supply","country":"澳大利亚","region":"大洋洲","cat":"client","coord":[150.90,-33.82],"cap":"多个 GWh 级 BESS 供货","inv":4,"invText":"约 4 亿美元","status":"在建","year":2026,"updated":"2025-11","owner":"宁德时代","flagship":false,"desc":"宁德时代为澳洲大型电池储能批量供货。","detail":"宁德时代(CATL)为澳大利亚快速增长的网级电池储能市场提供电芯与系统集成方案。2025 年 1-10 月中国储能企业在澳获得近 50GWh 订单，宁德时代是主要供货方之一，支撑澳洲跃居全球第三大公用事业储能市场，服务燃煤退役后的电网灵活性需求。","progress":"2025 年多个 GWh 级项目电芯交付推进"}
]);
