/* =============================================================
 * 全球能源项目世界地图 —— 英文正文（双语详情卡）
 * -------------------------------------------------------------
 * window.ENERGY_EN = { <id>: { descEn, detailEn } }，由 util.buildProjects 按 id 合并进项目，
 * 仅在源数据未内联 descEn/detailEn 时填充（与 progress.js 的按 id 合并同一模式）。
 * 这样英文翻译与源数据分离、互不污染，可分批增量补全（再加 i18n-en2.js 等并用 Object.assign 续接即可）。
 * EN 模式下详情卡正文走 descBody → detailEn || descEn；本文件主供 detailEn（卡片正文）。
 *
 * 批次 1：js/data.js 核心地标项目（id 1–87，墨脱/Stargate/北方气田/Simandou 等）。
 * 翻译为中文 detail 的对应英文，力求与既有内联英文（id 1/14/17）同一简洁事实风格。
 * 注：id 1/14/17 已在 data.js 内联英文，合并时不覆盖，故此处不重复收录。
 * ============================================================= */
window.ENERGY_EN = Object.assign(window.ENERGY_EN || {}, {
  /* ===== 可再生能源发电 ===== */
  7: { descEn: "A deep-water offshore wind cluster off Guangdong.", detailEn: "Off the coast of Yangjiang in Guangdong, the Qingzhou cluster is a flagship of China's large-scale deep-water offshore wind development, with sections progressively approved, started and grid-connected toward a planned ~7 GW total. It uses large-megawatt turbines with flexible HVDC export and pilots an integrated \"offshore wind + marine ranching + hydrogen\" model." },
  8: { descEn: "Planned to be the world's largest offshore wind base.", detailEn: "Chaozhou in Guangdong plans an ~43.3 GW mega offshore wind base in the wind-rich waters west of the Taiwan Strait; if realised it would be the world's largest offshore wind project. The strait's \"funnel effect\" yields world-class wind resources, though deep-water construction, long-distance transmission and ecological coordination remain key challenges." },
  12: { descEn: "One of the world's largest CSP complexes.", detailEn: "On the edge of the Sahara near Ouarzazate, Morocco, this concentrated-solar-power complex combines parabolic-trough and tower units totalling ~580 MW with molten-salt storage, letting it keep supplying power for several hours after sunset. A benchmark for African clean energy, it has sharply cut Morocco's dependence on imported fossil fuels." },
  13: { descEn: "One of Africa's largest solar parks.", detailEn: "In Benban, Aswan Governorate, Egypt, this park comprises about 40 separate plants totalling ~1.65 GW, making it one of Africa's largest solar parks. Built with support from the World Bank and other multilateral lenders, it drew global developers, markedly boosted Egypt's power supply and created local jobs." },
  15: { descEn: "A large solar-plus-storage project in Nevada.", detailEn: "On federal land northeast of Las Vegas, Nevada, Gemini pairs 690 MW of solar with 380 MW/1.4 GWh of battery storage, fully commissioned in 2024. One of the largest solar-plus-storage projects in the US at the time, it supplies clean power to the Las Vegas metro area and provides night-time output support." },
  16: { descEn: "The first commercial-scale US offshore wind farm.", detailEn: "South of Martha's Vineyard, Massachusetts, the 806 MW Vineyard Wind 1 is the first commercial-scale offshore wind farm in the US, built by Avangrid and Copenhagen Infrastructure Partners (CIP). Generating since late 2023 and connecting in stages, it powers about 400,000 New England homes and marks the launch of the US offshore wind industry." },

  /* ===== 输变电 · 电网 ===== */
  21: { descEn: "A new UHV corridor energised in June 2025.", detailEn: "Running ~2,260 km from Barkol in Hami, Xinjiang to Chongqing at ±800 kV with 8 GW capacity, this UHVDC line was energised on 10 June 2025. It bundles Xinjiang's desert wind, solar and thermal power for export to the southwest, delivering ~36 TWh a year to Chongqing — a landmark artery for large-scale renewable export from China's northwest." },
  22: { descEn: "A new west-to-east power corridor commissioning in 2026.", detailEn: "This ±800 kV, 8 GW UHVDC line carries power from Gansu to Zhejiang, with key converter equipment supplied by Hitachi Energy and others, targeting commissioning in 2026. Once online it will deliver about 36 TWh a year to Zhejiang — a high share of it renewable — easing the power shortfall in the Yangtze River Delta load centre." },
  23: { descEn: "Ningxia renewables exported to Hunan.", detailEn: "The \"Ningxia-to-Hunan\" UHVDC link runs ~1,600 km from Zhongwei in Ningxia to Hengyang in Hunan at 8 GW, the first UHV corridor in China designed primarily to carry renewable power, paired with large wind and solar bases in the Tengger Desert. It will deliver about 36 TWh a year to Hunan, more than half of it renewable." },
  29: { descEn: "The world's longest land-and-subsea HVDC interconnector.", detailEn: "Linking Lincolnshire in the UK with western Denmark, the ~765 km, 1.4 GW Viking Link is the world's longest combined onshore-and-subsea HVDC interconnector, commissioned in 2024. It lets UK wind power trade with Danish and Nordic hydro and wind, boosting the flexibility and security of both grids." },
  31: { descEn: "The largest clean-energy transmission project in US history.", detailEn: "SunZia combines a 3.5 GW onshore wind farm in New Mexico with an ~885 km, ±525 kV HVDC line carrying the power to Arizona and into the California market — at about $11 billion the largest clean-energy infrastructure project in US history. By early 2026 all 674 turbines had been delivered and installed, with the project nearing completion." },
  32: { descEn: "Quebec hydropower delivered directly to New York City.", detailEn: "A ~545 km, 1.25 GW buried and underwater HVDC line running along Lake Champlain and the Hudson River to bring Quebec's hydropower into New York City, with power flows planned from May 2026. It will meet about 20% of the city's electricity demand, sharply cutting local fossil-fuel reliance and emissions." },
  33: { descEn: "The Middle East's first large-scale HVDC interconnector.", detailEn: "Connecting Saudi Arabia and Egypt at ±500 kV with 3 GW capacity, this is the first large-scale HVDC interconnector in the Middle East and North Africa. The two countries' demand peaks fall at different times (Saudi summer daytime, Egyptian evening), so the link lets them share peaks and reserves, improving regional grid economics and stability." },
  34: { descEn: "First link between the Texas grid and the US Southeast.", detailEn: "A ~320-mile, 525 kV, 3 GW bidirectional HVDC line that for the first time connects the relatively isolated Texas ERCOT grid with the US Southeast. Once built, the two grids can support each other during extreme weather, markedly improving supply reliability — a key US inter-regional interconnection project." },

  /* ===== 储能 ===== */
  35: { descEn: "The largest pumped-hydro storage in the Southern Hemisphere.", detailEn: "In the Snowy Mountains of New South Wales, tunnels and reversible turbines are being added between existing reservoirs for 2.2 GW of capacity and about 350 GWh of storage — the largest pumped-hydro scheme in the Southern Hemisphere. It will provide long-duration backstop balancing for Australia's high-renewables grid, in effect a giant \"water battery\"." },
  36: { descEn: "One of the Southern Hemisphere's largest battery storage systems.", detailEn: "On a former power-station site in New South Wales, the 850 MW/1,680 MWh Waratah Super Battery is one of the largest battery storage projects in the Southern Hemisphere. Acting as a grid \"shock absorber\", it rapidly absorbs and injects power during line faults to protect transmission corridors, letting existing lines carry more renewable energy." },
  38: { descEn: "The world's largest battery project by GWh to date.", detailEn: "Announced in February 2026 by Xcel Energy and Google using Form Energy's iron-air battery technology, this 300 MW/30 GWh system is the world's largest battery storage project by gigawatt-hours to date. Iron-air cells enable roughly 100 hours of long-duration storage, mainly providing multi-day reliable power to Minnesota's data centres and grid." },
  39: { descEn: "The world's first gigawatt-scale round-the-clock solar-plus-storage.", detailEn: "Developed by the UAE's Masdar with EWEC, this project pairs ~5.2 GW of solar with ~19 GWh of battery storage to deliver a steady 1 GW of round-the-clock (24/7) output — the world's first solar-plus-storage scheme at this scale. It aims to prove that solar plus batteries alone can supply near-baseload, reliable power." },
  40: { descEn: "A giant high-altitude battery storage system.", detailEn: "In India's high-altitude Ladakh region, this ~12 GWh system supports a large local renewable-energy base, smoothing output fluctuations and underpinning long-distance transmission. One of India's largest battery storage projects, it serves as a model for grid stability at high altitude." },
  41: { descEn: "A giant storage project in the Atacama Desert.", detailEn: "Built by Spain's Grenergy in Chile's Atacama Desert, this project deploys about 11 GWh of battery storage in phases alongside large-scale solar. Shifting abundant daytime sunshine to night-time release, it is one of Latin America's largest storage projects, helping Chile's grid wean off fossil-fuelled peaking plants." },
  43: { descEn: "The world's largest compressed-air energy storage.", detailEn: "In Yingcheng, Hubei, this plant uses a single 300 MW unit storing compressed air in underground salt caverns — at commissioning in 2024 the world's largest and most efficient non-combustion compressed-air energy storage station. It charts a new path for long-duration, high-capacity, low-cost storage and exemplifies the diversification of new storage technologies." },
  44: { descEn: "One of the world's largest single battery storage projects.", detailEn: "Large battery storage deployed by the Saudi Electricity Company across several sites including Bisha, with multi-GWh batches supplied by BYD and others — among the world's largest single battery storage projects. It absorbs Saudi Arabia's fast-growing solar capacity and underpins the high-renewables targets of Vision 2030." },

  /* ===== 工商业 · 配网大客户 ===== */
  46: { descEn: "The largest semiconductor investment in the US.", detailEn: "TSMC is building several advanced-process fabs in Phoenix, Arizona, with cumulative pledged investment raised to about $165 billion — the largest foreign semiconductor investment in US history. A single fab's power and water needs rival a mid-sized city, driving large-scale expansion of local grid and water systems and anchoring a full semiconductor supply chain." },
  47: { descEn: "A mega \"Silicon Heartland\" fab campus.", detailEn: "Near Columbus, Ohio, Intel plans a mega fab campus dubbed the \"Silicon Heartland\", with initial investment of about $28 billion. Its production timeline has slipped amid the semiconductor market downturn, but it remains a major project for domestic advanced-process manufacturing and grid capacity expansion." },
  49: { descEn: "India's first large-scale wafer fab.", detailEn: "The Tata Group, with Taiwan's PSMC, is building India's first large-scale wafer fab at Dholera, Gujarat, for about $11 billion. A flagship of India's chip self-reliance strategy, it comes with dedicated power, ultra-pure water and a new industrial city, creating huge new demand on the local grid and infrastructure." },

  /* ===== 数据中心 ===== */
  50: { descEn: "The largest AI infrastructure build in the US.", detailEn: "A joint venture of OpenAI, Oracle, SoftBank and MGX, Stargate plans to invest up to $500 billion by 2029 to build about 10 GW of AI computing. Its first flagship campus is in Abilene, Texas, and by 2025-2026 it had expanded to around 10 sites across Texas, New Mexico, Ohio and Michigan. Its staggering power demand (several GW per campus) is reshaping US power planning and spurring matching generation and storage investment." },
  51: { descEn: "An AI supercomputing centre in Memphis.", detailEn: "Elon Musk's xAI is building the \"Colossus\" supercomputing cluster in Memphis, Tennessee, deploying hundreds of thousands of GPUs to train large models and scaling toward gigawatt-class power demand. The project has drawn local scrutiny over temporary gas generation, power and water use — a microcosm of the grid pressure from rapid AI compute expansion." },
  52: { descEn: "The largest AI data-centre cluster outside the US.", detailEn: "In Abu Dhabi, the UAE's G42 is building this cluster with Nvidia, OpenAI, Cisco, Oracle and others, planning about 5 GW of compute — the largest AI data-centre cluster outside the US, entering service in phases from 2026. Leveraging cheap local energy and capital, the UAE aims to become the Middle East's artificial-intelligence and computing hub." },
  53: { descEn: "The world's densest concentration of data centres.", detailEn: "Around Ashburn in Loudoun County, Virginia lies the world's densest cluster of data centres, carrying a sizeable share of global internet traffic, with total power use already above 5 GW and still growing. AWS, Microsoft, Google and others are packed in here, and their power demand has forced major adjustments to local grid and generation planning." },
  54: { descEn: "Southeast Asia's fastest-growing data-centre hub.", detailEn: "Johor in Malaysia, next to Singapore, is absorbing data-centre demand spilling over from land- and power-constrained Singapore, with capacity under construction already reaching several GW — Southeast Asia's fastest-growing data-centre hub. Major cloud and AI firms are investing heavily here, driving rapid expansion of local power, solar and supporting infrastructure." },
  55: { descEn: "A Middle East AI computing centre.", detailEn: "Backed by Saudi Arabia's sovereign wealth fund, HUMAIN is building large-scale AI data centres in Riyadh and elsewhere with Nvidia, AMD and others, planning several GW of compute. Leveraging cheap energy and capital, Saudi Arabia aims to make computing a new pillar of its Vision 2030 economy." },

  /* ===== 大交通 · 轨交机场港口 ===== */
  59: { descEn: "A flagship China-CEE railway.", detailEn: "Connecting Budapest in Hungary with Belgrade in Serbia, this ~350 km electrified, upgraded-speed railway already has its Belgrade-Novi Sad section in service. A flagship of China-Central and Eastern Europe cooperation and the Belt and Road in Europe, it will improve the efficiency of the China-Europe Land-Sea Express route." },
  61: { descEn: "A new South America-Asia shipping hub.", detailEn: "North of Lima, Peru, and built and operated by COSCO Shipping, Chancay is the first smart, green deep-water mega-port on South America's west coast, opening in November 2024. Its direct route to Shanghai cuts shipping time from Peru to China by about 10 days, reshaping South America-Asia trade and driving green port infrastructure such as shore power." },
  62: { descEn: "Planned to be one of the world's largest airports.", detailEn: "Led by Saudi Arabia's PIF sovereign fund, this airport is planned with six runways and an eventual annual throughput of up to 185 million passengers, set to be one of the world's largest. It is core infrastructure for Riyadh's ambition to become a global aviation and logistics hub and to support the economic diversification of Vision 2030." },
  63: { descEn: "Vietnam's largest airport.", detailEn: "In Dong Nai Province east of Ho Chi Minh City, Long Thanh's first phase is due in 2026 with 25 million passengers a year, expanding to 100 million long term, making it Vietnam's largest airport. It will relieve pressure on Tan Son Nhat, strengthen Vietnam's position as a regional aviation hub and spur surrounding industry and power supply." },
  64: { descEn: "Sydney's second airport.", detailEn: "In Sydney's western suburbs, Western Sydney Airport is due to open in the second half of 2026 with an initial 10 million passengers a year, becoming Sydney's second international airport. It comes with a dedicated metro line, roads and power networks, easing the capacity bottleneck at Kingsford Smith Airport and driving development of Western Sydney." },
  65: { descEn: "Europe's largest air-rail hub under construction.", detailEn: "Between Warsaw and Łódź, the Central Communication Port (CPK) is planned with two parallel runways integrated with a high-speed-rail hub and motorway network, at about €30 billion, with construction from 2026, serving a catchment of some 21 million people. It is set to be Central and Eastern Europe's largest combined aviation and high-speed-rail hub, with rail offering an \"air-to-rail\" alternative." },
  66: { descEn: "The first true high-speed rail in the US.", detailEn: "Planned to link San Francisco and Los Angeles, California High-Speed Rail is under full construction along a 119-mile segment in the Central Valley, with most structures built or under way — the first true high-speed railway in the US. Repeatedly challenged on schedule and budget, it is seen as a pivotal attempt to modernise US passenger rail." },
  68: { descEn: "The China-Pakistan Economic Corridor's sea gateway.", detailEn: "On the Arabian Sea coast of Balochistan, Pakistan, Gwadar is the sea gateway of the China-Pakistan Economic Corridor (CPEC), with a free-trade zone, power plant and desalination facilities. Once complete it offers western China a shorter route to the Indian Ocean and drives local energy and infrastructure development." },

  /* ===== 石油化工 · LNG ===== */
  69: { descEn: "The world's largest LNG expansion project.", detailEn: "Drawing on the world's largest single gas field — the North Field — Qatar is lifting LNG output from about 77 million tonnes a year to roughly 142 million tonnes before 2030 via its East and South phases and further expansion. It is the world's largest LNG expansion, further cementing Qatar's position as the leading global LNG exporter." },
  70: { descEn: "A large export LNG terminal in Louisiana.", detailEn: "A large export LNG project by Venture Global in Calcasieu, Louisiana; in March 2026 its second phase reached final investment decision with about $8.6 billion of financing secured. It is emblematic of the 2025-2026 wave of new US LNG investment, further expanding US gas export capacity to Europe and Asia." },
  71: { descEn: "A large export LNG terminal in Louisiana.", detailEn: "Near the mouth of the Mississippi River in Louisiana, Plaquemines LNG has capacity of about 24 million tonnes a year, using modular construction for fast start-up and beginning phased LNG output in 2024-2025. One of Venture Global's flagship export terminals, it is helping make the US the world's largest LNG exporter." },
  72: { descEn: "A Gulf Coast LNG terminal advancing toward FID.", detailEn: "Energy Transfer is converting its existing import terminal at Lake Charles, Louisiana into an export terminal of about 16.5 million tonnes a year, advancing toward a final investment decision in early 2026 after locking in several long-term supply agreements. It is another important reserve of US LNG export capacity." },
  73: { descEn: "North Slope gas liquefied for export.", detailEn: "Led by Glenfarne, Alaska LNG would pipe abundant North Slope gas about 800 miles to Nikiski on the Kenai Peninsula for liquefaction and export, at a total cost of about $44 billion. With gas supply secured from major oil-and-gas players and a final investment decision advancing in 2026, it could offer shorter-haul LNG to Asian markets." },
  74: { descEn: "An LNG capacity expansion at Kitimat.", detailEn: "At Kitimat, British Columbia, operated by a Shell-led joint venture, the first phase is already producing and exporting LNG to Asia, with the phase-2 expansion advancing toward a final investment decision in 2026. Thanks to Canada's shorter west-coast route to Asia, it is an important addition to North American LNG supply to Asia." },
  76: { descEn: "The world's largest single-train refinery.", detailEn: "In the Lekki Free Trade Zone near Lagos, Nigeria, the Dangote Refinery processes 650,000 barrels a day — the world's largest single-train refinery — starting up from 2024. It reverses West Africa's long reliance on imported fuels, positioning Nigeria to shift from a crude exporter to a net exporter of refined products, with its own captive power plant and jetty." },
  77: { descEn: "The core of Saudi Arabia's \"gas-for-oil\" strategy.", detailEn: "In eastern Saudi Arabia, Jafurah is the Middle East's largest unconventional (shale) gas field, which Saudi Aramco plans to develop in phases for about $100 billion. The added gas will go to power, industry and blue-hydrogen production, freeing up more crude for export — the centrepiece of Saudi Arabia's \"gas-for-oil\" energy strategy." },
  78: { descEn: "A gravity-based LNG plant in the Arctic Circle.", detailEn: "On the Gydan Peninsula inside Russia's Arctic Circle and led by Novatek, Arctic LNG 2 uses modular liquefaction trains built on gravity-based structures (GBS), with planned capacity of about 20 million tonnes a year. Hit by Western sanctions, it has struggled with equipment, shipping and sales — a textbook case of geopolitics' impact on energy projects." },

  /* ===== 矿业 ===== */
  80: { descEn: "The largest high-grade iron-ore mine under development.", detailEn: "In the mountains of south-eastern Guinea, Simandou grades about 65.8% iron — one of the largest and highest-grade undeveloped iron-ore deposits in the world. Blocks 1-2 are led by the Chinese-backed WCS consortium and Blocks 3-4 by a Rio Tinto-Chinalco venture, served by the ~620 km TransGuinéen heavy-haul railway and a new port. The first ore shipped in December 2025 and reached Zhejiang in January 2026, with output ramping toward ~120 million tonnes a year, reshaping global iron-ore supply." },
  81: { descEn: "The world's highest-output copper mine.", detailEn: "In Chile's Atacama Desert, operated by BHP with Rio Tinto and others as partners, Escondida is the world's highest-output copper mine. Recent years have seen about $13 billion invested in expansion, desalination and processing upgrades, and it now runs on 100% renewable power — vital to the copper supply needed for the global energy transition." },
  86: { descEn: "The hub of global iron-ore supply.", detailEn: "The Pilbara region of Western Australia is the hub of global iron-ore supply, where Rio Tinto, BHP, FMG and others run multiple super-large mines exporting over a billion tonnes a year, mostly to China. The region's extensive use of autonomous haul trucks, driverless heavy-haul trains and remote operations centres makes it a benchmark for mining automation." },
  87: { descEn: "A frontier of new global lithium supply.", detailEn: "The \"Lithium Triangle\" where Argentina, Chile and Bolivia meet holds over half the world's lithium resources, with relatively low-cost brine extraction. Chinese firms such as Zijin and Ganfeng, together with international miners, are building brine lithium projects intensively in Argentina, making the region a leading frontier of new global lithium supply." },
});
