/* =============================================================
 * 全球能源项目世界地图 —— 英文正文（双语详情卡）
 * -------------------------------------------------------------
 * window.ENERGY_EN = { <id>: { descEn, detailEn } }，由 util.buildProjects 按 id 合并进项目，
 * 仅在源数据未内联 descEn/detailEn 时填充（与 progress.js 的按 id 合并同一模式）。
 * 这样英文翻译与源数据分离、互不污染，可分批增量补全（再加 i18n-en2.js 等并用 Object.assign 续接即可）。
 * EN 模式下详情卡正文走 descBody → detailEn || descEn；本文件主供 detailEn（卡片正文）。
 *
 * 批次 1：js/data.js 核心地标项目（id 1–87，墨脱/Stargate/北方气田/Simandou 等）。
 * 翻译为中文 detail 的对应英文，力求与既有内联英文（id 1/14/17）同一简洁事实风格。
 * 注：id 1/14/17 已在 data.js 内联英文，合并时不覆盖，故此处不重复收录。
 * ============================================================= */
window.ENERGY_EN = Object.assign(window.ENERGY_EN || {}, {
  /* ===== 可再生能源发电 ===== */
  7: { descEn: "A deep-water offshore wind cluster off Guangdong.", detailEn: "Off the coast of Yangjiang in Guangdong, the Qingzhou cluster is a flagship of China's large-scale deep-water offshore wind development, with sections progressively approved, started and grid-connected toward a planned ~7 GW total. It uses large-megawatt turbines with flexible HVDC export and pilots an integrated \"offshore wind + marine ranching + hydrogen\" model." },
  8: { descEn: "Planned to be the world's largest offshore wind base.", detailEn: "Chaozhou in Guangdong plans an ~43.3 GW mega offshore wind base in the wind-rich waters west of the Taiwan Strait; if realised it would be the world's largest offshore wind project. The strait's \"funnel effect\" yields world-class wind resources, though deep-water construction, long-distance transmission and ecological coordination remain key challenges." },
  12: { descEn: "One of the world's largest CSP complexes.", detailEn: "On the edge of the Sahara near Ouarzazate, Morocco, this concentrated-solar-power complex combines parabolic-trough and tower units totalling ~580 MW with molten-salt storage, letting it keep supplying power for several hours after sunset. A benchmark for African clean energy, it has sharply cut Morocco's dependence on imported fossil fuels." },
  13: { descEn: "One of Africa's largest solar parks.", detailEn: "In Benban, Aswan Governorate, Egypt, this park comprises about 40 separate plants totalling ~1.65 GW, making it one of Africa's largest solar parks. Built with support from the World Bank and other multilateral lenders, it drew global developers, markedly boosted Egypt's power supply and created local jobs." },
  15: { descEn: "A large solar-plus-storage project in Nevada.", detailEn: "On federal land northeast of Las Vegas, Nevada, Gemini pairs 690 MW of solar with 380 MW/1.4 GWh of battery storage, fully commissioned in 2024. One of the largest solar-plus-storage projects in the US at the time, it supplies clean power to the Las Vegas metro area and provides night-time output support." },
  16: { descEn: "The first commercial-scale US offshore wind farm.", detailEn: "South of Martha's Vineyard, Massachusetts, the 806 MW Vineyard Wind 1 is the first commercial-scale offshore wind farm in the US, built by Avangrid and Copenhagen Infrastructure Partners (CIP). Generating since late 2023 and connecting in stages, it powers about 400,000 New England homes and marks the launch of the US offshore wind industry." },

  /* ===== 输变电 · 电网 ===== */
  21: { descEn: "A new UHV corridor energised in June 2025.", detailEn: "Running ~2,260 km from Barkol in Hami, Xinjiang to Chongqing at ±800 kV with 8 GW capacity, this UHVDC line was energised on 10 June 2025. It bundles Xinjiang's desert wind, solar and thermal power for export to the southwest, delivering ~36 TWh a year to Chongqing — a landmark artery for large-scale renewable export from China's northwest." },
  22: { descEn: "A new west-to-east power corridor commissioning in 2026.", detailEn: "This ±800 kV, 8 GW UHVDC line carries power from Gansu to Zhejiang, with key converter equipment supplied by Hitachi Energy and others, targeting commissioning in 2026. Once online it will deliver about 36 TWh a year to Zhejiang — a high share of it renewable — easing the power shortfall in the Yangtze River Delta load centre." },
  23: { descEn: "Ningxia renewables exported to Hunan.", detailEn: "The \"Ningxia-to-Hunan\" UHVDC link runs ~1,600 km from Zhongwei in Ningxia to Hengyang in Hunan at 8 GW, the first UHV corridor in China designed primarily to carry renewable power, paired with large wind and solar bases in the Tengger Desert. It will deliver about 36 TWh a year to Hunan, more than half of it renewable." },
  29: { descEn: "The world's longest land-and-subsea HVDC interconnector.", detailEn: "Linking Lincolnshire in the UK with western Denmark, the ~765 km, 1.4 GW Viking Link is the world's longest combined onshore-and-subsea HVDC interconnector, commissioned in 2024. It lets UK wind power trade with Danish and Nordic hydro and wind, boosting the flexibility and security of both grids." },
  31: { descEn: "The largest clean-energy transmission project in US history.", detailEn: "SunZia combines a 3.5 GW onshore wind farm in New Mexico with an ~885 km, ±525 kV HVDC line carrying the power to Arizona and into the California market — at about $11 billion the largest clean-energy infrastructure project in US history. By early 2026 all 674 turbines had been delivered and installed, with the project nearing completion." },
  32: { descEn: "Quebec hydropower delivered directly to New York City.", detailEn: "A ~545 km, 1.25 GW buried and underwater HVDC line running along Lake Champlain and the Hudson River to bring Quebec's hydropower into New York City, with power flows planned from May 2026. It will meet about 20% of the city's electricity demand, sharply cutting local fossil-fuel reliance and emissions." },
  33: { descEn: "The Middle East's first large-scale HVDC interconnector.", detailEn: "Connecting Saudi Arabia and Egypt at ±500 kV with 3 GW capacity, this is the first large-scale HVDC interconnector in the Middle East and North Africa. The two countries' demand peaks fall at different times (Saudi summer daytime, Egyptian evening), so the link lets them share peaks and reserves, improving regional grid economics and stability." },
  34: { descEn: "First link between the Texas grid and the US Southeast.", detailEn: "A ~320-mile, 525 kV, 3 GW bidirectional HVDC line that for the first time connects the relatively isolated Texas ERCOT grid with the US Southeast. Once built, the two grids can support each other during extreme weather, markedly improving supply reliability — a key US inter-regional interconnection project." },

  /* ===== 储能 ===== */
  35: { descEn: "The largest pumped-hydro storage in the Southern Hemisphere.", detailEn: "In the Snowy Mountains of New South Wales, tunnels and reversible turbines are being added between existing reservoirs for 2.2 GW of capacity and about 350 GWh of storage — the largest pumped-hydro scheme in the Southern Hemisphere. It will provide long-duration backstop balancing for Australia's high-renewables grid, in effect a giant \"water battery\"." },
  36: { descEn: "One of the Southern Hemisphere's largest battery storage systems.", detailEn: "On a former power-station site in New South Wales, the 850 MW/1,680 MWh Waratah Super Battery is one of the largest battery storage projects in the Southern Hemisphere. Acting as a grid \"shock absorber\", it rapidly absorbs and injects power during line faults to protect transmission corridors, letting existing lines carry more renewable energy." },
  38: { descEn: "The world's largest battery project by GWh to date.", detailEn: "Announced in February 2026 by Xcel Energy and Google using Form Energy's iron-air battery technology, this 300 MW/30 GWh system is the world's largest battery storage project by gigawatt-hours to date. Iron-air cells enable roughly 100 hours of long-duration storage, mainly providing multi-day reliable power to Minnesota's data centres and grid." },
  39: { descEn: "The world's first gigawatt-scale round-the-clock solar-plus-storage.", detailEn: "Developed by the UAE's Masdar with EWEC, this project pairs ~5.2 GW of solar with ~19 GWh of battery storage to deliver a steady 1 GW of round-the-clock (24/7) output — the world's first solar-plus-storage scheme at this scale. It aims to prove that solar plus batteries alone can supply near-baseload, reliable power." },
  40: { descEn: "A giant high-altitude battery storage system.", detailEn: "In India's high-altitude Ladakh region, this ~12 GWh system supports a large local renewable-energy base, smoothing output fluctuations and underpinning long-distance transmission. One of India's largest battery storage projects, it serves as a model for grid stability at high altitude." },
  41: { descEn: "A giant storage project in the Atacama Desert.", detailEn: "Built by Spain's Grenergy in Chile's Atacama Desert, this project deploys about 11 GWh of battery storage in phases alongside large-scale solar. Shifting abundant daytime sunshine to night-time release, it is one of Latin America's largest storage projects, helping Chile's grid wean off fossil-fuelled peaking plants." },
  43: { descEn: "The world's largest compressed-air energy storage.", detailEn: "In Yingcheng, Hubei, this plant uses a single 300 MW unit storing compressed air in underground salt caverns — at commissioning in 2024 the world's largest and most efficient non-combustion compressed-air energy storage station. It charts a new path for long-duration, high-capacity, low-cost storage and exemplifies the diversification of new storage technologies." },
  44: { descEn: "One of the world's largest single battery storage projects.", detailEn: "Large battery storage deployed by the Saudi Electricity Company across several sites including Bisha, with multi-GWh batches supplied by BYD and others — among the world's largest single battery storage projects. It absorbs Saudi Arabia's fast-growing solar capacity and underpins the high-renewables targets of Vision 2030." },

  /* ===== 工商业 · 配网大客户 ===== */
  46: { descEn: "The largest semiconductor investment in the US.", detailEn: "TSMC is building several advanced-process fabs in Phoenix, Arizona, with cumulative pledged investment raised to about $165 billion — the largest foreign semiconductor investment in US history. A single fab's power and water needs rival a mid-sized city, driving large-scale expansion of local grid and water systems and anchoring a full semiconductor supply chain." },
  47: { descEn: "A mega \"Silicon Heartland\" fab campus.", detailEn: "Near Columbus, Ohio, Intel plans a mega fab campus dubbed the \"Silicon Heartland\", with initial investment of about $28 billion. Its production timeline has slipped amid the semiconductor market downturn, but it remains a major project for domestic advanced-process manufacturing and grid capacity expansion." },
  49: { descEn: "India's first large-scale wafer fab.", detailEn: "The Tata Group, with Taiwan's PSMC, is building India's first large-scale wafer fab at Dholera, Gujarat, for about $11 billion. A flagship of India's chip self-reliance strategy, it comes with dedicated power, ultra-pure water and a new industrial city, creating huge new demand on the local grid and infrastructure." },

  /* ===== 数据中心 ===== */
  50: { descEn: "The largest AI infrastructure build in the US.", detailEn: "A joint venture of OpenAI, Oracle, SoftBank and MGX, Stargate plans to invest up to $500 billion by 2029 to build about 10 GW of AI computing. Its first flagship campus is in Abilene, Texas, and by 2025-2026 it had expanded to around 10 sites across Texas, New Mexico, Ohio and Michigan. Its staggering power demand (several GW per campus) is reshaping US power planning and spurring matching generation and storage investment." },
  51: { descEn: "An AI supercomputing centre in Memphis.", detailEn: "Elon Musk's xAI is building the \"Colossus\" supercomputing cluster in Memphis, Tennessee, deploying hundreds of thousands of GPUs to train large models and scaling toward gigawatt-class power demand. The project has drawn local scrutiny over temporary gas generation, power and water use — a microcosm of the grid pressure from rapid AI compute expansion." },
  52: { descEn: "The largest AI data-centre cluster outside the US.", detailEn: "In Abu Dhabi, the UAE's G42 is building this cluster with Nvidia, OpenAI, Cisco, Oracle and others, planning about 5 GW of compute — the largest AI data-centre cluster outside the US, entering service in phases from 2026. Leveraging cheap local energy and capital, the UAE aims to become the Middle East's artificial-intelligence and computing hub." },
  53: { descEn: "The world's densest concentration of data centres.", detailEn: "Around Ashburn in Loudoun County, Virginia lies the world's densest cluster of data centres, carrying a sizeable share of global internet traffic, with total power use already above 5 GW and still growing. AWS, Microsoft, Google and others are packed in here, and their power demand has forced major adjustments to local grid and generation planning." },
  54: { descEn: "Southeast Asia's fastest-growing data-centre hub.", detailEn: "Johor in Malaysia, next to Singapore, is absorbing data-centre demand spilling over from land- and power-constrained Singapore, with capacity under construction already reaching several GW — Southeast Asia's fastest-growing data-centre hub. Major cloud and AI firms are investing heavily here, driving rapid expansion of local power, solar and supporting infrastructure." },
  55: { descEn: "A Middle East AI computing centre.", detailEn: "Backed by Saudi Arabia's sovereign wealth fund, HUMAIN is building large-scale AI data centres in Riyadh and elsewhere with Nvidia, AMD and others, planning several GW of compute. Leveraging cheap energy and capital, Saudi Arabia aims to make computing a new pillar of its Vision 2030 economy." },

  /* ===== 大交通 · 轨交机场港口 ===== */
  59: { descEn: "A flagship China-CEE railway.", detailEn: "Connecting Budapest in Hungary with Belgrade in Serbia, this ~350 km electrified, upgraded-speed railway already has its Belgrade-Novi Sad section in service. A flagship of China-Central and Eastern Europe cooperation and the Belt and Road in Europe, it will improve the efficiency of the China-Europe Land-Sea Express route." },
  61: { descEn: "A new South America-Asia shipping hub.", detailEn: "North of Lima, Peru, and built and operated by COSCO Shipping, Chancay is the first smart, green deep-water mega-port on South America's west coast, opening in November 2024. Its direct route to Shanghai cuts shipping time from Peru to China by about 10 days, reshaping South America-Asia trade and driving green port infrastructure such as shore power." },
  62: { descEn: "Planned to be one of the world's largest airports.", detailEn: "Led by Saudi Arabia's PIF sovereign fund, this airport is planned with six runways and an eventual annual throughput of up to 185 million passengers, set to be one of the world's largest. It is core infrastructure for Riyadh's ambition to become a global aviation and logistics hub and to support the economic diversification of Vision 2030." },
  63: { descEn: "Vietnam's largest airport.", detailEn: "In Dong Nai Province east of Ho Chi Minh City, Long Thanh's first phase is due in 2026 with 25 million passengers a year, expanding to 100 million long term, making it Vietnam's largest airport. It will relieve pressure on Tan Son Nhat, strengthen Vietnam's position as a regional aviation hub and spur surrounding industry and power supply." },
  64: { descEn: "Sydney's second airport.", detailEn: "In Sydney's western suburbs, Western Sydney Airport is due to open in the second half of 2026 with an initial 10 million passengers a year, becoming Sydney's second international airport. It comes with a dedicated metro line, roads and power networks, easing the capacity bottleneck at Kingsford Smith Airport and driving development of Western Sydney." },
  65: { descEn: "Europe's largest air-rail hub under construction.", detailEn: "Between Warsaw and Łódź, the Central Communication Port (CPK) is planned with two parallel runways integrated with a high-speed-rail hub and motorway network, at about €30 billion, with construction from 2026, serving a catchment of some 21 million people. It is set to be Central and Eastern Europe's largest combined aviation and high-speed-rail hub, with rail offering an \"air-to-rail\" alternative." },
  66: { descEn: "The first true high-speed rail in the US.", detailEn: "Planned to link San Francisco and Los Angeles, California High-Speed Rail is under full construction along a 119-mile segment in the Central Valley, with most structures built or under way — the first true high-speed railway in the US. Repeatedly challenged on schedule and budget, it is seen as a pivotal attempt to modernise US passenger rail." },
  68: { descEn: "The China-Pakistan Economic Corridor's sea gateway.", detailEn: "On the Arabian Sea coast of Balochistan, Pakistan, Gwadar is the sea gateway of the China-Pakistan Economic Corridor (CPEC), with a free-trade zone, power plant and desalination facilities. Once complete it offers western China a shorter route to the Indian Ocean and drives local energy and infrastructure development." },

  /* ===== 石油化工 · LNG ===== */
  69: { descEn: "The world's largest LNG expansion project.", detailEn: "Drawing on the world's largest single gas field — the North Field — Qatar is lifting LNG output from about 77 million tonnes a year to roughly 142 million tonnes before 2030 via its East and South phases and further expansion. It is the world's largest LNG expansion, further cementing Qatar's position as the leading global LNG exporter." },
  70: { descEn: "A large export LNG terminal in Louisiana.", detailEn: "A large export LNG project by Venture Global in Calcasieu, Louisiana; in March 2026 its second phase reached final investment decision with about $8.6 billion of financing secured. It is emblematic of the 2025-2026 wave of new US LNG investment, further expanding US gas export capacity to Europe and Asia." },
  71: { descEn: "A large export LNG terminal in Louisiana.", detailEn: "Near the mouth of the Mississippi River in Louisiana, Plaquemines LNG has capacity of about 24 million tonnes a year, using modular construction for fast start-up and beginning phased LNG output in 2024-2025. One of Venture Global's flagship export terminals, it is helping make the US the world's largest LNG exporter." },
  72: { descEn: "A Gulf Coast LNG terminal advancing toward FID.", detailEn: "Energy Transfer is converting its existing import terminal at Lake Charles, Louisiana into an export terminal of about 16.5 million tonnes a year, advancing toward a final investment decision in early 2026 after locking in several long-term supply agreements. It is another important reserve of US LNG export capacity." },
  73: { descEn: "North Slope gas liquefied for export.", detailEn: "Led by Glenfarne, Alaska LNG would pipe abundant North Slope gas about 800 miles to Nikiski on the Kenai Peninsula for liquefaction and export, at a total cost of about $44 billion. With gas supply secured from major oil-and-gas players and a final investment decision advancing in 2026, it could offer shorter-haul LNG to Asian markets." },
  74: { descEn: "An LNG capacity expansion at Kitimat.", detailEn: "At Kitimat, British Columbia, operated by a Shell-led joint venture, the first phase is already producing and exporting LNG to Asia, with the phase-2 expansion advancing toward a final investment decision in 2026. Thanks to Canada's shorter west-coast route to Asia, it is an important addition to North American LNG supply to Asia." },
  76: { descEn: "The world's largest single-train refinery.", detailEn: "In the Lekki Free Trade Zone near Lagos, Nigeria, the Dangote Refinery processes 650,000 barrels a day — the world's largest single-train refinery — starting up from 2024. It reverses West Africa's long reliance on imported fuels, positioning Nigeria to shift from a crude exporter to a net exporter of refined products, with its own captive power plant and jetty." },
  77: { descEn: "The core of Saudi Arabia's \"gas-for-oil\" strategy.", detailEn: "In eastern Saudi Arabia, Jafurah is the Middle East's largest unconventional (shale) gas field, which Saudi Aramco plans to develop in phases for about $100 billion. The added gas will go to power, industry and blue-hydrogen production, freeing up more crude for export — the centrepiece of Saudi Arabia's \"gas-for-oil\" energy strategy." },
  78: { descEn: "A gravity-based LNG plant in the Arctic Circle.", detailEn: "On the Gydan Peninsula inside Russia's Arctic Circle and led by Novatek, Arctic LNG 2 uses modular liquefaction trains built on gravity-based structures (GBS), with planned capacity of about 20 million tonnes a year. Hit by Western sanctions, it has struggled with equipment, shipping and sales — a textbook case of geopolitics' impact on energy projects." },

  /* ===== 矿业 ===== */
  80: { descEn: "The largest high-grade iron-ore mine under development.", detailEn: "In the mountains of south-eastern Guinea, Simandou grades about 65.8% iron — one of the largest and highest-grade undeveloped iron-ore deposits in the world. Blocks 1-2 are led by the Chinese-backed WCS consortium and Blocks 3-4 by a Rio Tinto-Chinalco venture, served by the ~620 km TransGuinéen heavy-haul railway and a new port. The first ore shipped in December 2025 and reached Zhejiang in January 2026, with output ramping toward ~120 million tonnes a year, reshaping global iron-ore supply." },
  81: { descEn: "The world's highest-output copper mine.", detailEn: "In Chile's Atacama Desert, operated by BHP with Rio Tinto and others as partners, Escondida is the world's highest-output copper mine. Recent years have seen about $13 billion invested in expansion, desalination and processing upgrades, and it now runs on 100% renewable power — vital to the copper supply needed for the global energy transition." },
  86: { descEn: "The hub of global iron-ore supply.", detailEn: "The Pilbara region of Western Australia is the hub of global iron-ore supply, where Rio Tinto, BHP, FMG and others run multiple super-large mines exporting over a billion tonnes a year, mostly to China. The region's extensive use of autonomous haul trucks, driverless heavy-haul trains and remote operations centres makes it a benchmark for mining automation." },
  87: { descEn: "A frontier of new global lithium supply.", detailEn: "The \"Lithium Triangle\" where Argentina, Chile and Bolivia meet holds over half the world's lithium resources, with relatively low-cost brine extraction. Chinese firms such as Zijin and Ganfeng, together with international miners, are building brine lithium projects intensively in Argentina, making the region a leading frontier of new global lithium supply." },
});

/* ===== 批次2：全库投资额 TOP（约 ≥175 亿美元）===== */
Object.assign(window.ENERGY_EN, {
  1033: { descEn: "The largest semiconductor project in US history.", detailEn: "Micron is building a mega-campus of four DRAM fabs at the White Pine Business Park in Clay, New York, with about $100 billion of investment — the largest semiconductor manufacturing project in US history — plus the first publicly owned High-NA EUV lithography centre in the country. Groundbreaking was held in January 2026, with first output targeted for 2030 and the full campus by the 2040s, driving city-scale grid and water expansion in central New York." },
  2047: { descEn: "A trans-isthmus land bridge bypassing the Strait of Malacca.", detailEn: "Thailand's Land Bridge would build deep-water ports at Chumphon and Ranong, linked by an 89 km six-lane expressway plus standard- and metre-gauge rail to bypass the Strait of Malacca. Costing about 1 trillion baht under a single 50-year PPP concession, it aims to start tendering and construction in 2026 with the first phase open by 2030 (internal rate of return ~17.4%)." },
  1539: { descEn: "Rosneft's Arctic flagship, with phase 1 targeted for 2026.", detailEn: "Vostok Oil is Rosneft's Arctic super-cluster of oilfields on the Taymyr Peninsula, valued at about $85 billion with planned investment of over 12 trillion roubles. Trial production began in early 2025 at fields such as Payakhskoye, with an export port, oil terminal and field pipelines under construction (over 80% done by September 2025); phase 1 is slated for 2026 and output is targeted at ~67 million tonnes a year by 2030." },
  1138: { descEn: "The UK's largest railway project.", detailEn: "HS2 is Britain's largest post-war rail infrastructure project, with phase 1 linking London's Old Oak Common to Birmingham at 330 km/h. Several tunnels broke through in 2025 — including the Bromford, Northolt and the line's longest Chiltern tunnel — and all deep bored tunnels between London and Birmingham were completed by October; civil works are about two-thirds done, with services planned for the early 2030s." },
  2933: { descEn: "Four AP1000 reactors anchoring an 11 GW AI campus in Texas.", detailEn: "Dubbed the 'Trump Advanced Energy and Intelligence Campus', this project beside the DOE Pantex plant near Amarillo, Texas plans up to 11 GW of gas, solar, storage and nuclear to power 18 million sq ft of AI computing. In 2025 the NRC accepted a combined licence for four AP1000 units, with the first targeted to start construction in 2026 and operate by April 2031." },
  2934: { descEn: "Westinghouse's plan for 10 US AP1000 units (~11.5 GW).", detailEn: "In July 2025 Westinghouse announced 10 AP1000 reactors in the US to help quadruple US nuclear capacity to 400 GW by 2050. In October 2025 the US government, Brookfield and Cameco signed a framework to invest at least $80 billion, and in April 2026 a Vogtle-4-standardised AP1000 design revision was filed. (Located at the Vogtle plant, Georgia.)" },
  3152: { descEn: "Transmission master plan for ~76 GW of Brahmaputra-basin hydropower.", detailEn: "Led by India's CEA, this ~6.4 trillion-rupee plan adds over 31,400 circuit-km of lines, ~68 GVA of substation capacity and 42 GW of HVDC to evacuate some 76 GW of hydro and pumped storage across 12 sub-basins including Siang (18.7 GW), Subansiri (12.3 GW) and Dibang (8.8 GW), in two phases around 2035." },
  3014: { descEn: "Canada's first true high-speed rail.", detailEn: "Announced by the Prime Minister in February 2025, Alto is a ~1,000 km dedicated electrified line at 300 km/h linking Toronto, Ottawa, Montreal and Quebec City. The private Cadence consortium (including SNCF and Air Canada) will design, build, finance and operate it; the design phase is ~C$3.9 billion and the whole network is estimated at C$60-90 billion, with main works around 2030." },
  162: { descEn: "The world's largest planned green-hydrogen export hub.", detailEn: "Spanning ~2.26 million hectares in Western Australia, this hub plans 70 GW of wind and solar to produce ~3.5 million tonnes of green hydrogen and 20 million tonnes of green ammonia a year. It won federal 'Major Project' status in March 2025, with a ~6 GW first phase tied to feasibility deals with China's SANY and Korean firms; fully built it would generate more than Australia's entire current output." },
  1161: { descEn: "Vietnam's 1,541 km north-south high-speed railway.", detailEn: "Vietnam's North-South high-speed railway links Hanoi and Ho Chi Minh City over 1,541 km through 15 provinces with 23 stations at 350 km/h. Approved by the National Assembly in November 2024 at about $67.5 billion across 17 sub-projects, construction was brought forward to December 2025 with a 2035 target, cutting Hanoi-HCMC travel to ~5.5 hours — the largest infrastructure project in Vietnam's history." },
  2938: { descEn: "Up to 4,800 MW added at the world's largest operating nuclear site.", detailEn: "Bruce C would add up to 4,800 MW within the existing Bruce site — Ontario's first major new-build nuclear in over 30 years. It has cleared the federal impact-assessment planning phase and entered the impact-statement stage, with Bruce Power signing a C$300 million pre-development deal; lifetime economic contribution is estimated at ~C$238 billion." },
  1546: { descEn: "A giant Baltic gas-processing, LNG and petrochemical complex.", detailEn: "The Ust-Luga complex, built by RusKhimAlliance (a 50/50 JV of Gazprom and RusGazDobycha), is designed to process 45 bcm of ethane-rich gas a year into 13 million tonnes of LNG, 3.6 million tonnes of ethane and up to 1.8 million tonnes of LPG, feeding an adjacent cracker producing over 3 million tonnes of polymers. Costing about 4.9 trillion roubles, it has been delayed by Western sanctions, with Linde withdrawing in 2022." },
  521: { descEn: "A 1.8 GW AI campus in Cheyenne, Wyoming.", detailEn: "Announced by Crusoe and Tallgrass in July 2025 in Laramie County southeast of Cheyenne, Project Jade plans 1.8 GW — expandable to 10 GW long term — with Tallgrass supplying a gas power plant. With total project cost potentially reaching $50 billion, it is one of the largest AI data centres under discussion in the US interior." },
  2800: { descEn: "The UK's first new nuclear plant in decades (2×EPR).", detailEn: "In Somerset, England, Hinkley Point C is two 1.6 GW EPR reactors led by EDF (with CGN as a partner) — the UK's first new nuclear station in decades. The second reactor dome was lifted in 2025 and its pressure vessel arrived in January 2026; with costs risen to about £46 billion, the first unit is due to operate in the early 2030s." },
  2803: { descEn: "France's nuclear restart: the first six EPR2 reactors.", detailEn: "EDF's next-generation EPR2 programme will build a first batch of six 1.67 GW reactors at Penly (2), Gravelines (2) and Bugey (2). Public consultation and early works advanced in 2025, with Penly 1/2 aiming for the mid-2030s — a national flagship to restart French nuclear and secure low-carbon baseload power." },
  3002: { descEn: "Anthropic's $50 billion compute build, starting in Texas and New York.", detailEn: "Announced on 12 November 2025, Anthropic's $50 billion US AI-infrastructure plan will build custom data centres with the UK's Fluidstack in Texas and New York, coming online from 2026 and creating about 800 long-term jobs, running alongside AWS, Google TPU and Microsoft Azure capacity." },
  2801: { descEn: "Sizewell C: FID taken in July 2025, UK government holds 44.9%.", detailEn: "In Suffolk, England, Sizewell C is two 1.6 GW EPR reactors replicating Hinkley Point C to cut costs. A final investment decision was taken in July 2025 at over £38 billion, with the UK government the largest shareholder at 44.9% and a regulated-asset-base (RAB) model bringing in private investment — a centrepiece of Britain's energy-security strategy." },
  1528: { descEn: "Kazakhstan's largest oilfield expansion, with a third processing train online.", detailEn: "Chevron-led Tengizchevroil's Future Growth Project (FGP) and Wellhead Pressure Management Project (WPMP) added a third-generation processing plant with enhanced sour-gas reinjection at the Tengiz field in western Kazakhstan. WPMP finished in 2024 and FGP started up in January 2025, ramping Tengiz to about 1 million barrels a day; at ~$46.7 billion it is Kazakhstan's largest single industrial investment." },
  1459: { descEn: "One of the world's largest green-hydrogen projects (40 GW + 20 GW electrolysis).", detailEn: "Sweden's Svevind, through Hyrasia One, plans about 40 GW of wind and solar in Kazakhstan's Mangystau region — ~120 TWh a year — feeding a 20 GW electrolyser park on the Caspian coast for up to 2 million tonnes of green hydrogen annually. Costing $40-50 billion, output is planned from 2030 with full capacity around 2032 and a final investment decision expected in 2026." },
  3562: { descEn: "The world's most challenging railway; over 84% bridges and tunnels.", detailEn: "The 1,019 km Ya'an-Nyingchi section of the Sichuan-Tibet Railway includes 72 new tunnels totalling 838 km (the 42.5 km Yigong tunnel the longest), at an estimated ~320 billion yuan. Early works such as key tunnels and bridges have begun, with completion targeted for 2030 and high-standard advancement set out in the 15th Five-Year Plan." },
  2418: { descEn: "A $42 billion LNG plant at Lindi, fed by Shell and Equinor offshore gas.", detailEn: "At Likong'o in Lindi, this plant would produce about 10 million tonnes of LNG a year from Shell (Blocks 1 and 4) and Equinor (Block 2) offshore reserves, at about $42 billion — Tanzania's largest single energy project. Parties are pushing to finalise the legal framework and FID by late 2025/early 2026, though FID risks slipping to 2028 with start-up after 2032." },
  158: { descEn: "One of the world's largest planned green-hydrogen projects.", detailEn: "This project plans 30 GW of wind and solar in Mauritania's desert to produce 1.7 million tonnes of green hydrogen a year, led by Australia's CWP Global. Geological, hydrological and marine surveys were completed in 2025 (pre-FEED stage), and once built it is expected to lift Mauritania's GDP by 40-50%." },
  513: { descEn: "Three new Google data-centre campuses in West Texas ($40 billion).", detailEn: "In November 2025 Google announced a $40 billion investment (through 2027) in three data centres in West Texas and the Panhandle — two in Haskell County (one a solar-plus-storage industrial park with Intersect) and one in Armstrong County — alongside contracts for 6,200+ MW of new power." },
  1027: { descEn: "A new 12-inch fab mega-site in Texas.", detailEn: "Texas Instruments is building a mega-site of up to four connected 12-inch fabs in Sherman, Texas, with potential total investment of ~$40 billion. The first fab, SM1, started production on 17 December 2025 — in just three and a half years — ramping toward tens of millions of analog and embedded chips a day, with SM2's shell topped out; the site is a city-scale new load on the local grid." },
  1518: { descEn: "Eastern expansion of the BAM and Trans-Siberian railways.", detailEn: "Russia approved a third phase of its Eastern rail network (the 'Eastern Polygon') to 2035 at over 3.7 trillion roubles (~$40 billion), aiming to lift eastbound capacity to 270 million tonnes a year within a decade. Works include new passing loops, tunnels, an Amur River bridge and spurs to Far East ports — a key corridor for exports to Asia-Pacific." },
  2374: { descEn: "Storage and grid infrastructure for the 30 GW AMAN green-hydrogen project.", detailEn: "CWP Global's flagship AMAN project in Mauritania plans 30 GW of wind and solar (18 GW wind + 12 GW solar) generating ~110 TWh a year to make 1.7 million tonnes of green hydrogen and 10 million tonnes of green ammonia, worth about $40 billion. It includes large-scale desalination, storage and transmission aimed at clean-energy export to Europe (this entry focuses on the renewables-and-storage build-out)." },
  2804: { descEn: "Poland's first nuclear power station (3×AP1000).", detailEn: "On Poland's Baltic coast, the state company PEJ is building three 1.25 GW AP1000 reactors with Westinghouse and Bechtel — Poland's first nuclear plant. It won site-preparation and survey permits in August-September 2025, and in December the EU approved state aid (including a 40-year contract for difference); the first unit is due to start construction in 2028 and operate in 2036." },
  3013: { descEn: "A Dallas-Houston high-speed line using Japanese Shinkansen technology.", detailEn: "This ~386 km, 330 km/h line lost federal planning funding and Amtrak's involvement in April 2025, returning to private leadership under Fort Worth investor John Kleinheinz. Station sites are bought and about 500 of ~2,000 parcels acquired, with cost estimated at over $40 billion." },
  3129: { descEn: "The world's largest planned nuclear plant (6×EPR).", detailEn: "At Madban in Ratnagiri, Maharashtra, NPCIL leads with EDF supplying six EPR reactors (~1,650 MW each, ~9.9 GW total), which would make it the world's largest planned nuclear station. President Macron's February 2026 visit to India confirmed advancing the six-EPR process with accompanying small-reactor cooperation." },
  3275: { descEn: "A giant west-coast refining-petrochemical complex, now being split up.", detailEn: "RRPCL — formed by IOCL/BPCL/HPCL (50:25:25) with Saudi Aramco and ADNOC to hold 50% — originally planned 60 million tonnes/year of refining plus 18 million tonnes of petrochemicals. Hit by land and environmental protests, the centre is from 2025 considering splitting it into three dispersed 20-million-tonne refineries, but it remains central to India's refining expansion." },
  565: { descEn: "The Wuhu cluster of China's 'east-data-west-compute' Yangtze Delta hub.", detailEn: "Since approval in 2022 the Wuhu cluster has attracted 15 major projects from Huawei Cloud, ByteDance, China Mobile and others totalling over 270 billion yuan, with 21,000 racks built and over 100,000 under construction. China Mobile's first nationwide 'four-compute-in-one' scheduling platform is here, targeting over 45,000 PFLOPS of AI computing by 2027." },
  588: { descEn: "Spain's largest-ever foreign investment, across three Aragon provinces.", detailEn: "In March 2026 Spain announced that Amazon will invest a cumulative €33.7 billion in the Aragon region, building large-scale data centres and server-manufacturing facilities across Zaragoza, Huesca and Teruel, expected to add €31.7 billion in GDP and an average 29,900 full-time jobs a year." },
  288: { descEn: "The world's largest planned single AI data centre.", detailEn: "South Jeolla Province in Korea has attracted a 3 GW, ~$35 billion AI data centre able to house 200,000 GPUs, breaking ground in winter 2025 with completion targeted for 2028, backed by Korea's 65-trillion-won national AI strategy." },
  1129: { descEn: "Planned to be the world's largest airport (150M pax phase 1).", detailEn: "Dubai's Al Maktoum International Airport phase-2 expansion, approved in 2024 at about AED 128 billion (~$35 billion), will build a central terminal and four concourses for 150 million passengers a year initially, rising to five runways, ~400 gates and 260 million passengers — the world's largest airport. A ~$272 million second-runway contract and early works were awarded in 2025, with phase 1 targeted for 2032." },
  2251: { descEn: "Six green hydrogen/ammonia/steel projects worth $32.8 billion.", detailEn: "In March 2025 Morocco approved a green-hydrogen package in which consortia led by Ortus (US)/Acciona/Nordex, TAQA/Cepsa, Morocco's Nareva, Saudi ACWA Power and a Chinese UEAG/Three Gorges group will produce green ammonia, fuels and green steel. Concentrated in the south (Guelmim, Tan-Tan, Boujdour), it adds ~6 GW of wind and solar, targeting 10 TWh of exports by 2030." },
  2983: { descEn: "Intel's 18A flagship fab at Chandler, now in production.", detailEn: "Fab 52, the fifth high-volume fab at Intel's Ocotillo campus in Chandler, Arizona, began carrying 18A wafers in October 2025 and entered high-volume manufacturing by year-end, producing the first 18A Panther Lake processors that launched in late 2025 with broad availability in early 2026." },
  1409: { descEn: "Jeddah airport expanded to one of the world's largest (114M pax by 2031).", detailEn: "Jeddah Airports Company's 115 billion-riyal (~$31 billion) plan will make King Abdulaziz International one of the world's largest airports, reaching 114 million passengers a year by 2031. It includes a T1 expansion, a new T2 (construction from 2026, over $10 billion), a fourth runway (2025-2029), a new logistics zone and a Hajj terminal." },
  161: { descEn: "The world's largest planned solar-plus-storage, with a 4,300 km cable to Singapore.", detailEn: "SunCable's project would deploy 17-20 GW of solar and 36-42 GWh of storage on the Barkly Tableland in Australia's Northern Territory, sending power to Singapore via Indonesia through a ~4,300 km subsea cable. It renewed 'Major Project' status in July 2025 and won Indonesian approval, targeting cross-border supply in the mid-2030s — among the largest single renewable projects ever planned." },
  1500: { descEn: "Central Asia's largest compute park (1 GW long term).", detailEn: "In Ekibastuz, Pavlodar region, this aims to be Central Asia's largest data-centre park, with power capacity of 300 MW initially rising to 1 GW and total investment of ~$30 billion. Run by Kazakhtelecom's KT-Telecom and powered by the Ekibastuz GRES plants, it launched in January 2026 with full construction due to start in June 2026; the government is in talks with Microsoft, OpenAI, G42 and Mubadala." },
  2825: { descEn: "The Arab world's first nuclear plant (4×APR1400, all online).", detailEn: "At Barakah in western Abu Dhabi, KEPCO built four 1.4 GW APR1400 reactors — the Arab world's first nuclear plant, at about $30 billion. The fourth unit was commissioned in 2025; with all four in commercial operation they supply about a quarter of the UAE's electricity, a Middle East nuclear benchmark." },
  2827: { descEn: "Egypt and Africa's first large nuclear plant (4×VVER).", detailEn: "At El Dabaa on Egypt's Mediterranean coast in Matrouh, Russia's Rosatom is building four 1.2 GW VVER-1200 reactors — Egypt and Africa's first large nuclear plant, at about $30 billion, with all four units built concurrently. Main works advanced rapidly in 2025, with the first unit targeted to operate around 2028." },
  2984: { descEn: "Micron's second advanced DRAM fab at Boise, with HBM packaging.", detailEn: "Micron is building a second advanced DRAM fab (ID2) next to R&D at its Boise headquarters campus — part of a ~$200 billion US expansion with ~$30 billion added here. Idaho and New York together won ~$6.1 billion in CHIPS grants, bringing advanced packaging to support the HBM that AI requires." },
  3130: { descEn: "An India-US flagship nuclear plant (6×AP1000).", detailEn: "At Kovvada in Srikakulam, Andhra Pradesh, India plans six Westinghouse AP1000 reactors (~1,100 MW each); about 2,080 acres have been acquired and transferred to NPCIL and surveys completed. In 2025 NPCIL continued technical-commercial talks with Westinghouse — a flagship of India-US civil-nuclear cooperation." },
  3577: { descEn: "Shenzhen's largest-ever metro build (phase 5, 13 lines).", detailEn: "Shenzhen's fifth-phase metro plan (2023-2028) covers 13 projects totalling 185.6 km at about 195.2 billion yuan, including lines 15, 17-22, 25, 27, 29 and 32 plus extensions of lines 10 and 11. On completion Shenzhen's rail network will reach 25 lines and about 843.6 km." },
  1514: { descEn: "Russia's first dedicated high-speed railway.", detailEn: "This 679 km line with 16 stations is designed for 400 km/h (360 km/h in service), linking Moscow and St Petersburg, at over 2.3 trillion roubles (~$26 billion) including low-interest National Wealth Fund loans. Approved by Putin in March 2024, construction began in summer 2025 with the first section due in 2028, cutting travel time from ~4 hours to 2h15." },
  506: { descEn: "AWS AI cloud data centres across several Mississippi counties.", detailEn: "AWS is building data centres in Madison County (Project Atlas, $11 billion), Vicksburg in Warren County ($3 billion) and sites in Hinds County, Mississippi, announced through 2025-2026 for a cumulative $25 billion — the largest AWS expansion in the US Southeast." },
  508: { descEn: "The second-largest Stargate site, in Shackelford County, Texas.", detailEn: "Vantage Data Centers is building the Frontier campus in Shackelford County north of Abilene, Texas — 1,200 acres, 10 buildings totalling 3.7 million sq ft and 1.4 GW of compute, using a gas microgrid and water-saving closed-loop cooling. Construction began in September 2025 and it is officially confirmed as a Stargate site." },
  580: { descEn: "One of the world's largest AI data-centre plans, with gigawatt-scale green power.", detailEn: "Reliance plans up to 3 GW of AI data centres at Jamnagar, Gujarat, using Nvidia's latest Blackwell GPUs and powered entirely by on-site solar, wind and green hydrogen, at an estimated $20-30 billion. Targeting a first phase within 24 months, it would be one of the world's largest green AI computing bases." },
  1547: { descEn: "A giant LNG base on the Kola Peninsula with a 1,300 km feed pipeline.", detailEn: "Novatek's Murmansk LNG on the Kola Peninsula has capacity of about 20.4 MTPA, with a cost edge because it needs no icebreakers for year-round export. In January 2025 completion was brought forward from 2033 to 2030, with phase 1 in 2027-2029, fed by a ~1,300 km Volkhov-Murmansk pipeline (4.12 bcm/year) that Putin ordered finished by 2030." },
  2302: { descEn: "A 5,000 km trans-Atlantic gas pipeline from West Africa to Europe.", detailEn: "Nigeria and Morocco plan a 5,000 km coastal gas pipeline through 13 West African countries toward Europe. The two aim to sign an intergovernmental agreement in Q4 2026 — one of Africa's most ambitious cross-border energy infrastructure projects." },
  2810: { descEn: "The world's largest tokamak fusion experiment.", detailEn: "At Cadarache in southern France, ITER is built by China, the EU, the US, Russia, Japan, Korea and India — the world's largest magnetic-confinement tokamak, designed for 500 MW of fusion power. Key components such as superconducting magnets were completed in 2025, with first plasma targeted around 2034 and full operation by 2039 to prove fusion power feasible." },
  2935: { descEn: "A framework to deploy up to 6 GW of NuScale SMRs with TVA.", detailEn: "ENTRA1 and TVA reached a non-binding agreement to develop and own six energy plants across a seven-state service area, deploying up to 6 GW of NuScale modular reactors, part of ENTRA1's ~$25 billion power-infrastructure plan, at the planning stage. (Located in the central TVA service area.)" },
  3144: { descEn: "A reserve Westinghouse AP1000 site in Gujarat (long term).", detailEn: "At Chhaya-Mithi Virdi on the coast of Bhavnagar, Gujarat, India originally planned six Westinghouse AP1000 reactors (~6 GW). Blocked by land acquisition, the main effort moved to Kovvada in Andhra Pradesh, but Westinghouse says it still intends to build six AP1000 units here once Kovvada is done — a long-term reserve site." },
  3578: { descEn: "Guangzhou Metro phase 4 (8 lines, 175.5 km).", detailEn: "Guangzhou's fourth-phase plan (2025-2031) covers eight line segments totalling 175.5 km at about 172.1 billion yuan, reinforcing high-load central lines and strengthening the eastern centre and Nansha networks. Environmental review began in October 2024, with approval targeted for 2026." },
  1164: { descEn: "Thailand's first high-speed railway, linking to the China-Laos line.", detailEn: "The China-Thailand high-speed railway is Thailand's first, about 609 km at 250 km/h in two phases. Phase 1 (Bangkok-Nakhon Ratchasima, 251 km) was about 45% complete on civil works by June 2025, targeting 2027; phase 2 (357 km to Nong Khai) was approved in February 2025 at ~341 billion baht for 2025-2032. Connecting to the China-Laos railway, it opens the Pan-Asian central corridor from Bangkok via Vientiane to China." },
  1224: { descEn: "A large greenfield refinery in East Java.", detailEn: "At Tuban in East Java, the PRPP joint venture of Pertamina and Rosneft is designed for 300,000 barrels a day plus a large petrochemical complex, at about $24 billion. Although FID remains unsettled due to the Russian partner, the project launched EPCC prequalification tendering in May 2026 — an important reserve of Indonesian refining capacity." },
  3047: { descEn: "The Trans Mountain crude pipeline expansion, online in May 2024.", detailEn: "The Trans Mountain Expansion entered service on 1 May 2024 after 12 years and about C$34 billion, raising capacity from 300,000 to 890,000 barrels a day from Edmonton to the port of Burnaby. Since start-up China has overtaken the US as the largest buyer, sharply lifting Canadian crude exports." },
  2743: { descEn: "Europe's largest metro project: four new Paris lines.", detailEn: "The Grand Paris Express is an automated metro network around Paris, building about 200 km of new lines (15/16/17/18) and 68 new stations at ~€36 billion — Europe's largest urban rail project. Tunnelling and station works are advancing, with some lines opening after the 2024 Olympics and the main network targeted for around 2030." },
  1400: { descEn: "The world's largest single-phase driverless metro.", detailEn: "Riyadh Metro comprises 6 lines and 85 stations over 176 km — the largest metro network built in a single phase and the world's longest fully automated driverless system. The Blue, Yellow and Purple lines opened on 1 December 2024, the Red and Green on 15 December, and the Orange on 5 January 2025, completing the network." },
  3579: { descEn: "Chengdu Metro phase 5 (10 projects, ~199.8 km).", detailEn: "Chengdu's fifth-phase plan covers 10 projects totalling about 199.8 km, including extensions of lines 5, 9, 10, 12, 16, 18, 20, 22, 23 and 27. Several have entered tendering, with Sichuan's 15th Five-Year rail plan budgeting over 100 billion yuan." },
  876: { descEn: "India's first national green-hydrogen hub, inaugurated by Modi in 2025.", detailEn: "Near Visakhapatnam at Pudimadaka, Andhra Pradesh, NTPC Green Energy and the state government plan 20 GW of renewables producing 1,500 tonnes of green hydrogen a day plus green methanol, urea and SAF. PM Modi laid the foundation stone in January 2025, with core phase-1 infrastructure targeted for 2026." },
  2653: { descEn: "Melbourne's underground orbital rail, connecting radial lines.", detailEn: "The Suburban Rail Loop East (SRL East) is a ~26 km fully underground railway from Cheltenham to Box Hill, linking south-eastern radial lines with universities and medical centres. At about A$34 billion with tunnelling from 2025, it is the largest public-transport project in Victoria's history." },
  1982: { descEn: "The longest cross-border subsea HVDC for green power.", detailEn: "This link sends green power from a giant solar-plus-storage plant in Australia's Northern Territory to Singapore via a ~4,300 km subsea HVDC cable, able to supply ~1.75 GW — nearly a tenth of Singapore's demand. It won conditional Singapore EMA approval in October 2024 and an Indonesian route permit in 2025 (with a ~$2.5 billion Indonesian investment pledge), targeting power from 2035." },
  2950: { descEn: "A 3,631-mile 765 kV backbone across nine Midwest states.", detailEn: "Approved by MISO in December 2024, this package of 24 projects and 323 facilities builds a 3,631-mile 765 kV backbone across nine states, with benefits possibly exceeding $72 billion. Together with phase 1 it totals about $32 billion, with projects entering service in 2032-2034." },
  1189: { descEn: "A Saudi offshore mega-expansion, online in late 2025.", detailEn: "Marjan is a giant offshore field straddling the Saudi-Iran median line; its increment adds GOSP-4, 24 offshore platforms and export lines, raising capacity by 300,000 to about 800,000 barrels a day of Arabian Medium crude, with the Tanajib gas plant processing associated gas. Both started up together in December 2025 — a pillar of Saudi Arabia's 12-million-barrel maximum sustainable capacity." },
  2067: { descEn: "Indonesia's largest LNG project in development (Abadi).", detailEn: "INPEX's Abadi LNG in the Masela block, at about $21 billion, will build a 9.5 MTPA liquefaction plant. It received Indonesian environmental approval in February 2026, with FID set for 2026 and start-up targeted for 2030; it has signed LNG offtake heads of agreement with bp, PGN, PLN and Shell and is seeking up to $14 billion in project finance, with construction tenders from mid-2026." },
  281: { descEn: "France's largest single data-centre investment commitment.", detailEn: "In February 2025 Brookfield and Data4 announced over $20.7 billion over five years to develop AI data-centre infrastructure in France, covering several campuses around Paris in line with the French government's AI strategy." },
  361: { descEn: "A $20 billion landmark LNG project, fully restarting in 2026.", detailEn: "Taking FID in 2019 at Afungi in Cabo Delgado, Mozambique, this 13 MTPA project was about 40% complete when suspended in 2021 due to armed conflict. Full restart was announced on 29 January 2026, remobilising over 4,000 workers, with first LNG in 2029." },
  500: { descEn: "Meta's 5 GW Hyperion AI super-data-centre in Louisiana.", detailEn: "Meta is building the Hyperion AI super-data-centre in Richland Parish, Louisiana — over 4,000 acres planned for up to 5 GW (a 1.5 GW first phase by end-2027), with 10 gas plants and 2.5 GW of renewables. Built by Turner/DPR/Mortenson, it began construction in 2025." },
  585: { descEn: "Europe's largest planned AI campus, nuclear-powered.", detailEn: "Announced at the May 2025 'Choose France' summit, MGX, Bpifrance, Mistral AI and Nvidia formed a joint venture to build Europe's largest AI campus in the Paris region — a 1.4 GW first phase from late 2026, operating in 2028, expanded in June 2026 to 3 GW nationwide, running on low-carbon nuclear power." },
  592: { descEn: "A $20 billion Qatar sovereign-AI JV with Brookfield.", detailEn: "The Qatar Investment Authority's Qai, established in December 2025, formed a $20 billion joint venture with Brookfield to build integrated computing campuses in Qatar and strategic markets, leveraging Qatar's gas resources and its location at the crossroads of Europe, Asia and Africa." },
  1025: { descEn: "A new line at the world's largest fab campus.", detailEn: "Pyeongtaek is the world's largest semiconductor campus; its fourth fab P4 is being converted from foundry to a dedicated sixth-generation 1c DRAM line of about 80,000 wafers/month, also for HBM4. Conversion runs from late 2025 with production expected in 2026, plus some NAND lines switched to DRAM for AI servers; the campus consumes billions of kWh a year." },
  1028: { descEn: "A mega-expansion by China's leading DRAM maker.", detailEn: "CXMT is building a 12-inch DRAM mega-fab in Lingang, Shanghai, planned for 400,000-600,000 wafers/month — 2-3 times its Hefei headquarters — focused on high-end DDR5, LPDDR5X and HBM3 (a dedicated 50,000 wafers/month), advancing equipment localisation. It moved into substantive progress in March 2026, with tool install in the second half, mass production in 2027 and full capacity in 2028 — a huge new industrial load on the Lingang grid." },
  1761: { descEn: "A new 420 MW hyperscale campus in Jundiaí, São Paulo.", detailEn: "In October 2025 Scala announced a new data-centre campus in Jundiaí planned for 420 MW, with up to $20 billion including direct customer investment, separate from its Tamboré and Eldorado campuses. Creating about 2,500 construction jobs, it is positioned as a Latin American AI-computing and sustainability hub, phasing into service from 2027." },
  2652: { descEn: "A 1,700 km freight rail spine along Australia's east coast.", detailEn: "Inland Rail is a 1,700+ km freight network linking Melbourne and Brisbane at about A$31 billion, built in segments. Using an inland corridor to cut east-coast freight times and improve supply chains, some segments are open and the Melbourne-Parkes section continues — Australia's largest rail project." },
  2659: { descEn: "Australia's largest undeveloped gas field, backfilling the North West Shelf.", detailEn: "In the Browse Basin off Western Australia, this is one of Australia's largest undeveloped conventional gas resources, planned to backfill the existing North West Shelf (NWS) Karratha plant via a subsea pipeline to extend its LNG exports. Subject to environmental approval, it advanced assessment and commercial arrangements in 2025, targeting the 2030s." },
  2739: { descEn: "The EU's €20 billion plan for 4-5 AI 'gigafactories'.", detailEn: "The European Commission proposed in 2025 to invest €20 billion in 4-5 AI 'gigafactories' as an anchor to leverage €200 billion of AI investment. A call for interest drew 76 applications across 60 sites in 16 countries proposing over €230 billion; the formal tender slipped to early 2026, aiming to build a sovereign European AI computing base." },
  2826: { descEn: "Turkey's first nuclear power station (4×VVER-1200).", detailEn: "At Akkuyu in Mersin province, southern Turkey, Russia's Rosatom is building four 1.2 GW VVER-1200 reactors on a build-own-operate basis — Turkey's first nuclear plant, at about $20 billion. Russia added ~$9 billion of financing in 2025, with the first unit aiming to start generating in 2026, eventually supplying about 10% of Turkey's electricity." },
  3026: { descEn: "A 15.6 km new metro line across central Toronto.", detailEn: "The Ontario Line runs 15.6 km from Exhibition Place through downtown to Don Mills (connecting to Line 5), adding 15 stations, at about C$27 billion with over C$4 billion of federal funding. Twin tunnel boring in the downtown section launched in April 2026, with heavy works at four eastern stations, targeting completion in 2031." },
  3580: { descEn: "Chongqing Metro phase 5 (~200 km new lines).", detailEn: "Chongqing's fifth-phase plan adds about 200 km of new lines, with eight lines (including Line 16 phase 1 and several extensions) entering feasibility studies, aiming to bring lines under construction and operating to 850 km. Preliminary phase-5 research will be carried out during the 15th Five-Year period." },
  1542: { descEn: "The world's largest helium source, reaching full capacity in 2025.", detailEn: "The Amur Gas Processing Plant treats gas from the Power of Siberia pipeline across six 7-bcm trains; the fourth came online in 2024 and full design capacity of 42 bcm/year was reached in 2025. At capacity it yields 2.4 million tonnes of ethane, 1.5 million tonnes of LPG and 60 million m³ of helium a year — the world's largest helium base — feeding ethane to the neighbouring Amur GCC." },
  1191: { descEn: "South America's largest shale play, breaking output records in 2025.", detailEn: "In Argentina's Neuquén province, Vaca Muerta is the largest shale oil-and-gas play outside North America. In October 2025 Argentine crude output hit a record 859,500 barrels a day, with Vaca Muerta shale oil ~570,000 b/d, about two-thirds of the nation's total. With 38-40 rigs and over $18 billion of 2025-26 investment, it could top a million barrels a day before 2028, ranking among the world's top three shale plays." },
  2916: { descEn: "A 2,250 MW hydro plant on the Churchill River, Labrador.", detailEn: "On the Churchill River in Newfoundland and Labrador, Gull Island is a 2,250 MW plant with a financed total cost of about C$24.9 billion, a JV of Newfoundland Hydro (60%) and Hydro-Québec (40%) arising from the two provinces' landmark December 2024 memorandum, targeting operation in 2035." },
  2926: { descEn: "A 17-year, up-to-1,920 MW PPA from Talen to power AWS.", detailEn: "In June 2025 Talen and Amazon reached a 17-year, up-to-1,920 MW carbon-free power deal, shifting from a behind-the-meter to a front-of-meter grid structure, with Talen becoming a licensed retail supplier for AWS in Pennsylvania; the two also explore new on-site SMRs and uprates." },
  3499: { descEn: "CXMT Hefei phase-2 DRAM, China's bid for global #4.", detailEn: "CXMT is directing about 130 billion yuan of IPO proceeds into phase-2 wafer manufacturing, pushing its Hefei headquarters toward ~300,000 wafers/month by end-2025 (up ~50% year on year). The phase-2 building is under way and moving to the next process node, consolidating its position as the world's fourth-largest DRAM maker." },
  1179: { descEn: "The finale of Qatar's LNG expansion (North Field West).", detailEn: "The North Field West (NFW) project caps QatarEnergy's North Field expansions, with two 8-MTPA mega-trains adding ~16 million tonnes a year to push Qatar's total toward 142 million tonnes by the 2030s. In February 2026 the onshore liquefaction EPC was awarded to a Technip Energies-led consortium, with first cargo expected by end-2031." },
  1206: { descEn: "The world's largest coal-chemical project under construction.", detailEn: "In the Qingshui Industrial Park of Yulin, Shaanxi, this is the world's largest coal-chemical project under construction, with planned total investment of 126.2 billion yuan over ~13 km² converting 24+ million tonnes of coal a year. Phase 1 focuses on coal-to-ethylene-glycol and phase 2 (~175.9 billion yuan) on coal-to-olefins/aromatics and high-value materials; by September 2025 most phase-2 basic design and long-lead procurement were complete, aiming for a trillion-yuan coal-chemical cluster." },
  1403: { descEn: "Baghdad's first metro network (7 lines, 148 km).", detailEn: "In July 2024 an international consortium (Alstom, Systra, SNCF, Talgo, SENER and Deutsche Bank) won a $17.5 billion contract to build the Baghdad metro on a DBOMFT basis — 7 lines, 148 km and 64 stations, targeting May 2029. In July 2025 the government decided to reassess the financial and technical terms." },
  3220: { descEn: "Microsoft's largest India data-centre region (Hyderabad).", detailEn: "Microsoft announced in 2025 a $17.5 billion four-year (2026-2029) investment to expand AI and cloud infrastructure in India, on top of an earlier $3 billion pledge. Its new Hyderabad region has three availability zones and will be Microsoft's largest in India, due mid-2026, with more land bought in Pune." },
  248: { descEn: "Samsung's largest US investment: an advanced-process fab.", detailEn: "At Taylor, Texas, Samsung's first phase is about $17 billion (eventually up to $44 billion); the main structure was finished by late 2024, with EUV tools installed and risk production in 2026, and Tesla has contracted to use its AI-chip capacity." },
});

/* —— 后续批次在此点之上 Object.assign 续接（详见文件头）—— */
